pub mod analytics;
pub mod delta;
pub mod enriched;
pub mod forward;
pub mod identity;
pub mod ordered;
pub mod resolution;
pub mod reverse;

use anyhow::Result;

use crate::dag::{ViewDag, ViewNode};
use crate::model::{MappingDocument, Strategy};

/// Replace `CREATE OR REPLACE VIEW` with `CREATE MATERIALIZED VIEW IF NOT EXISTS`
/// in the generated SQL for a single view.
fn materialize_view_sql(view_sql: &str) -> String {
    view_sql.replace(
        "CREATE OR REPLACE VIEW",
        "CREATE MATERIALIZED VIEW IF NOT EXISTS",
    )
}

/// Emit a `CREATE UNIQUE INDEX IF NOT EXISTS` statement for a view.
///
/// `nulls_not_distinct` should be true when the key may contain NULL columns
/// (reverse and delta views where insert rows have NULL PKs).
fn emit_unique_index(view_name: &str, columns: &[&str], nulls_not_distinct: bool) -> String {
    let qi_view = crate::qi(view_name);
    let idx_name = crate::qi(&format!("idx_{view_name}"));
    let cols = columns
        .iter()
        .map(|c| crate::qi(c))
        .collect::<Vec<_>>()
        .join(", ");
    let nulls_clause = if nulls_not_distinct {
        "\n  NULLS NOT DISTINCT"
    } else {
        ""
    };
    format!(
        "CREATE UNIQUE INDEX IF NOT EXISTS {idx_name}\n  ON {qi_view} ({cols}){nulls_clause};\n"
    )
}

/// Render the complete SQL script for a mapping document.
///
/// When `create_tables` is true, emits `CREATE TABLE` statements for all
/// input tables (source datasets and cluster_members tables) so the output
/// is self-contained and can be executed in an empty Postgres database.
///
/// When `annotate` is true, emits inline comments before each view showing
/// which user-defined expressions, filters, and strategies drove the SQL.
///
/// When `materialize` is true, emits `CREATE MATERIALIZED VIEW IF NOT EXISTS`
/// instead of `CREATE OR REPLACE VIEW`, adds unique indexes per view, and
/// appends a `REFRESH MATERIALIZED VIEW CONCURRENTLY` script.
pub fn render_sql(
    doc: &MappingDocument,
    dag: &ViewDag,
    create_tables: bool,
    annotate: bool,
    materialize: bool,
) -> Result<String> {
    let mut sql = String::new();

    sql.push_str("-- Generated by osi-engine — OSI mapping reference engine\n");
    sql.push_str("-- Do not edit manually.\n\n");
    sql.push_str("BEGIN;\n\n");

    // Emit JSONB text-normalization helper when nested arrays are present.
    // This function recursively converts all scalar values to text/string
    // so noop detection can compare original JSONB (which may have native
    // integer/boolean types) against reconstructed JSONB (always text).
    let has_nested = doc.mappings.iter().any(|m| m.source.path.is_some());
    if has_nested {
        sql.push_str(
            "CREATE OR REPLACE FUNCTION _osi_text_norm(j jsonb) RETURNS jsonb\n\
             LANGUAGE plpgsql IMMUTABLE AS $$\n\
             BEGIN\n  \
               IF j IS NULL THEN RETURN NULL; END IF;\n  \
               CASE jsonb_typeof(j)\n    \
                 WHEN 'array' THEN\n      \
                   RETURN COALESCE(\n        \
                     (SELECT jsonb_agg(_osi_text_norm(elem) ORDER BY idx)\n         \
                      FROM jsonb_array_elements(j) WITH ORDINALITY AS t(elem, idx)),\n        \
                     '[]'::jsonb);\n    \
                 WHEN 'object' THEN\n      \
                   RETURN COALESCE(\n        \
                     (SELECT jsonb_object_agg(key, _osi_text_norm(value))\n         \
                      FROM jsonb_each(j)),\n        \
                     '{}'::jsonb);\n    \
                 WHEN 'null' THEN RETURN 'null'::jsonb;\n    \
                 ELSE RETURN to_jsonb(j #>> '{}');\n  \
               END CASE;\n\
             END;\n\
             $$;\n\n",
        );
    }

    // Track materialized view names for the refresh script.
    let mut mat_view_names: Vec<String> = Vec::new();

    for node in &dag.order {
        match node {
            ViewNode::Source(table_name) => {
                if create_tables {
                    sql.push_str(&render_input_table(doc, table_name));
                    sql.push('\n');
                }
            }
            ViewNode::Forward(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                let target_name = mapping.target.name();
                let target = doc.targets.get(target_name);
                let source_meta = doc.sources.get(&mapping.source.dataset);
                if annotate {
                    sql.push_str(&annotate_forward(mapping, target));
                }
                let nested_base_cols: Vec<String> = if mapping.source.path.is_none() {
                    let mut cols: Vec<String> = Vec::new();
                    for m in &doc.mappings {
                        if m.source.dataset == mapping.source.dataset && m.source.path.is_some() {
                            if let Some(ref p) = m.source.path {
                                let root = p.split('.').next().unwrap_or(p).to_string();
                                if !cols.contains(&root) {
                                    cols.push(root);
                                }
                            }
                        }
                    }
                    cols
                } else {
                    vec![]
                };
                // Collect canonical normalize expressions across all mappings
                // targeting the same entity so forward views emit consistent
                // _normalize columns for echo-aware resolution (Phase 2).
                let normalize_fields: std::collections::HashMap<String, String> = {
                    let mut map = std::collections::HashMap::new();
                    for m in &doc.mappings {
                        if m.target.name() == target_name {
                            for fm in &m.fields {
                                if let (Some(ref tgt), Some(ref norm)) = (&fm.target, &fm.normalize)
                                {
                                    map.entry(tgt.clone()).or_insert_with(|| norm.clone());
                                }
                            }
                        }
                    }
                    map
                };
                let mut view_sql = forward::render_forward_view(
                    mapping,
                    source_meta,
                    target,
                    &nested_base_cols,
                    &normalize_fields,
                    &doc.mappings,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    let is_array = mapping.array.is_some() || mapping.array_path.is_some();
                    let identity_cols: Vec<String> = if is_array {
                        target
                            .map(|t| {
                                t.fields
                                    .iter()
                                    .filter(|(_, fd)| fd.strategy() == Strategy::Identity)
                                    .map(|(name, _)| name.clone())
                                    .collect()
                            })
                            .unwrap_or_default()
                    } else {
                        vec![]
                    };
                    let mut idx_cols: Vec<&str> = vec!["_src_id"];
                    for col in &identity_cols {
                        idx_cols.push(col.as_str());
                    }
                    view_sql.push_str(&emit_unique_index(&vn, &idx_cols, false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Identity(target_name) => {
                let target = doc.targets.get(target_name);
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                if annotate {
                    sql.push_str(&annotate_identity(&mappings, target));
                }
                let fwd_names: Vec<String> = mappings
                    .iter()
                    .filter(|m| m.has_fields())
                    .map(|m| m.name.clone())
                    .collect();
                let mut view_sql = identity::render_identity_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.mappings,
                    &doc.sources,
                    &fwd_names,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_entity_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Resolved(target_name) => {
                let target = doc.targets.get(target_name).expect("target exists in dag");
                if annotate {
                    sql.push_str(&annotate_resolution(target));
                }
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                let mut view_sql = resolution::render_resolution_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.targets,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_entity_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Ordered(target_name) => {
                let target = doc.targets.get(target_name).expect("target exists in dag");
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                let mut view_sql = ordered::render_ordered_view(target_name, target, &mappings)?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_entity_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Analytics(target_name) => {
                let target = doc.targets.get(target_name).expect("target exists in dag");
                let has_enriched = dag
                    .edges
                    .contains_key(&ViewNode::Enriched(target_name.clone()));
                let mut view_sql =
                    analytics::render_analytics_view(target_name, target, has_enriched)?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_cluster_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Enriched(target_name) => {
                let target = doc.targets.get(target_name).expect("target exists in dag");
                let all_target_names: Vec<&str> = doc.targets.keys().map(|s| s.as_str()).collect();
                let has_mixed_order = dag
                    .edges
                    .contains_key(&ViewNode::Ordered(target_name.clone()));
                let mut view_sql = enriched::render_enriched_view(
                    target_name,
                    target,
                    &all_target_names,
                    has_mixed_order,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_entity_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Reverse(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                if annotate {
                    sql.push_str(&annotate_reverse(mapping));
                }
                let target_name = mapping.target.name();
                let target = doc.targets.get(target_name);
                let source_meta = doc.sources.get(&mapping.source.dataset);
                let has_enriched = dag
                    .edges
                    .contains_key(&ViewNode::Enriched(target_name.to_string()));
                let mut view_sql = reverse::render_reverse_view(
                    mapping,
                    target_name,
                    target,
                    &doc.targets,
                    source_meta,
                    &doc.mappings,
                    &doc.sources,
                    has_enriched,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_cluster_id", "_src_id"], true));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Delta(source_name) => {
                let source_mappings: Vec<&_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.source.dataset == *source_name && m.needs_sync())
                    .collect();
                if annotate {
                    sql.push_str(&format!("-- Delta for source: {source_name}\n"));
                }
                let source_meta = doc.sources.get(source_name.as_str());
                let mut view_sql = delta::render_delta_view(
                    source_name,
                    &source_mappings,
                    source_meta,
                    &doc.targets,
                    &doc.mappings,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    let mut key_cols: Vec<&str> = vec!["_cluster_id"];
                    if let Some(src) = source_meta {
                        for col in src.primary_key.columns() {
                            key_cols.push(col);
                        }
                    }
                    view_sql.push_str(&emit_unique_index(&vn, &key_cols, true));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
        }
    }

    // Emit refresh script when materializing.
    if materialize && !mat_view_names.is_empty() {
        sql.push_str("-- Refresh materialized views in dependency order\n");
        for vn in &mat_view_names {
            sql.push_str(&format!(
                "REFRESH MATERIALIZED VIEW CONCURRENTLY {};\n",
                crate::qi(vn)
            ));
        }
        sql.push('\n');
    }

    sql.push_str("COMMIT;\n");

    Ok(sql)
}

/// Render a CREATE TABLE statement for an input table.
///
/// Infer SQL column types from test input data for a given source dataset.
///
/// Scans all `tests[*].input.<dataset_key>` rows and returns a map from
/// column name → SQL type string.  The inference rules mirror the test
/// harness: String→TEXT, integer→BIGINT, float→DOUBLE PRECISION,
/// bool→BOOLEAN, array/object→JSONB, mixed→TEXT, all-null→TEXT.
fn infer_types_from_tests(
    doc: &MappingDocument,
    dataset_key: &str,
) -> std::collections::HashMap<String, &'static str> {
    let mut seen: std::collections::HashMap<String, Option<&'static str>> =
        std::collections::HashMap::new();

    // Helper: scan a slice of JSON rows, accumulating column→type info.
    let mut scan_rows = |rows: &[serde_json::Value]| {
        for row in rows {
            if let Some(obj) = row.as_object() {
                for (col, val) in obj {
                    // Skip engine-internal columns that don't belong in the
                    // physical input table.
                    if col == "_cluster_id" {
                        continue;
                    }
                    let kind = match val {
                        serde_json::Value::Null => continue,
                        serde_json::Value::String(_) => "TEXT",
                        serde_json::Value::Number(n) => {
                            if n.is_f64() && !n.is_i64() && !n.is_u64() {
                                "DOUBLE PRECISION"
                            } else {
                                "BIGINT"
                            }
                        }
                        serde_json::Value::Bool(_) => "BOOLEAN",
                        serde_json::Value::Array(_) | serde_json::Value::Object(_) => "JSONB",
                    };
                    let entry = seen.entry(col.clone()).or_insert(None);
                    match entry {
                        None => *entry = Some(kind),
                        Some(prev) if *prev == kind => {}
                        Some(prev) => *prev = "TEXT", // mixed types
                    }
                }
            }
        }
    };

    for test in &doc.tests {
        // Scan input rows.
        if let Some(rows) = test.input.get(dataset_key) {
            scan_rows(rows);
        }
        // Scan expected output rows (updates, inserts, deletes) — these may
        // contain columns written back by reverse/delta views (e.g.
        // reverse_only computed fields) that don't appear in input data.
        if let Some(expected) = test.expected.get(dataset_key) {
            scan_rows(&expected.updates);
            scan_rows(&expected.inserts);
            scan_rows(&expected.deletes);
        }
    }

    seen.into_iter()
        .map(|(col, kind)| (col, kind.unwrap_or("TEXT")))
        .collect()
}

/// For source datasets: emits `_row_id SERIAL` + PK columns + all source
/// columns referenced by field mappings + timestamp columns.
///
/// For cluster_members tables: emits the cluster_id and source_key columns.
///
/// Column types are resolved with the following priority:
/// 1. `source_path` columns → always JSONB
/// 2. Explicit `sources.<ds>.fields.<col>.type` declarations
/// 3. Inferred from test input data (JSON value types)
/// 4. Fallback → TEXT
fn render_input_table(doc: &MappingDocument, table_name: &str) -> String {
    use crate::qi;
    // Check if this is a cluster_members table
    for mapping in &doc.mappings {
        if let Some(ref cm) = mapping.cluster_members {
            if cm.table_name(&mapping.name) == table_name {
                return format!(
                    "-- Input table: {table_name} (cluster members)\n\
                     CREATE TABLE IF NOT EXISTS {} (\n  \
                                             {} TEXT PRIMARY KEY,\n  \
                                             {} TEXT\n\
                     );\n",
                    qi(table_name),
                    qi(&cm.source_key),
                    qi(&cm.cluster_id)
                );
            }
        }
    }

    // Check if this is a written_state table
    for mapping in &doc.mappings {
        if let Some(ref ws) = mapping.written_state {
            if ws.table_name(&mapping.name) == table_name {
                return format!(
                    "-- Input table: {table_name} (written state)\n\
                     CREATE TABLE IF NOT EXISTS {} (\n  \
                                             {} TEXT PRIMARY KEY,\n  \
                                             {} JSONB NOT NULL,\n  \
                                             {} TIMESTAMPTZ NOT NULL DEFAULT now(),\n  \
                                             {} JSONB NOT NULL DEFAULT '{{}}'::jsonb\n\
                     );\n",
                    qi(table_name),
                    qi(&ws.cluster_id),
                    qi(&ws.written),
                    qi(&ws.written_at),
                    qi(&ws.written_ts),
                );
            }
        }
    }

    // Source dataset table — collect all referenced columns.
    let mut columns: Vec<String> = Vec::new();

    // Resolve source metadata and dataset key by key or by explicit table override.
    let source_entry: Option<(&str, &crate::model::Source)> = doc
        .sources
        .get_key_value(table_name)
        .map(|(k, v)| (k.as_str(), v))
        .or_else(|| {
            doc.sources
                .iter()
                .find(|(key, src)| src.table_name(key) == table_name)
                .map(|(key, src)| (key.as_str(), src))
        });
    let source_meta = source_entry.map(|(_, src)| src);
    let dataset_key = source_entry.map(|(key, _)| key);

    // Add PK columns first so they are always present in generated DDL.
    let pk_columns: Vec<String> = source_meta
        .map(|source| {
            source
                .primary_key
                .columns()
                .into_iter()
                .map(|c| c.to_string())
                .collect()
        })
        .unwrap_or_default();
    for col in &pk_columns {
        if !columns.contains(col) {
            columns.push(col.clone());
        }
    }

    // Infer columns and types from test input and expected data.
    let inferred_types = dataset_key
        .map(|key| infer_types_from_tests(doc, key))
        .unwrap_or_default();

    // Test data is the authoritative source for column names — it
    // contains exactly the real top-level columns without synthetic
    // aliases from child/parent mappings.
    for col in inferred_types.keys() {
        if !columns.contains(col) {
            columns.push(col.clone());
        }
    }

    // Collect explicit type declarations from sources.<ds>.fields.<col>.type.
    let explicit_types: std::collections::HashMap<&str, &str> = source_meta
        .map(|src| {
            src.fields
                .iter()
                .filter_map(|(col, def)| def.field_type.as_deref().map(|t| (col.as_str(), t)))
                .collect()
        })
        .unwrap_or_default();

    let mut col_defs: Vec<String> = Vec::new();
    if pk_columns.is_empty() {
        // Fallback for mappings without declared source PK metadata.
        col_defs.push("_row_id SERIAL PRIMARY KEY".to_string());
    }
    col_defs.extend(columns.iter().map(|c| {
        let sql_type = if let Some(t) = explicit_types.get(c.as_str()) {
            // Priority 1: explicit type declaration from sources.fields.
            t
        } else if let Some(t) = inferred_types.get(c.as_str()) {
            // Priority 2: inferred from test input data.
            t
        } else {
            // Priority 3: fallback.
            "TEXT"
        };
        format!("{} {sql_type}", qi(c))
    }));
    if !pk_columns.is_empty() {
        col_defs.push(format!(
            "PRIMARY KEY ({})",
            pk_columns
                .iter()
                .map(|c| qi(c))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    format!(
        "-- Input table: {table_name}\n\
         CREATE TABLE IF NOT EXISTS {} (\n  {}\n);\n",
        qi(table_name),
        col_defs.join(",\n  ")
    )
}

// ---------------------------------------------------------------------------
// Annotation helpers — emit SQL comments showing user-defined configuration
// ---------------------------------------------------------------------------

use crate::model::{Mapping, Target};

/// Prefix every line of `text` with `-- ` so multi-line values stay commented.
fn comment_lines(text: &str) -> String {
    text.lines()
        .map(|l| format!("--   {l}"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn annotate_forward(m: &Mapping, _target: Option<&Target>) -> String {
    let mut lines = Vec::new();
    lines.push(format!(
        "-- [annotate] _fwd_{}: {} -> {}",
        m.name,
        m.source.dataset,
        m.target.name()
    ));
    for fm in &m.fields {
        if !fm.is_forward() {
            continue;
        }
        let tgt = fm.target.as_deref().unwrap_or("?");
        let src = fm.source.as_deref().unwrap_or("-");
        if let Some(ref e) = fm.expression {
            lines.push(comment_lines(&format!("{src} -> {tgt} (expression: {e})")));
        } else {
            lines.push(format!("--   {src} -> {tgt}"));
        }
    }
    if let Some(ref f) = m.filter {
        lines.push(comment_lines(&format!("filter: {f}")));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_identity(mappings: &[&Mapping], target: Option<&Target>) -> String {
    let mut lines = Vec::new();
    let target_name = mappings.first().map(|m| m.target.name()).unwrap_or("?");
    lines.push(format!("-- [annotate] _id_{target_name}: identity fields"));
    if let Some(t) = target {
        for (fname, fdef) in &t.fields {
            if fdef.strategy() == Strategy::Identity {
                lines.push(format!("--   {fname} (identity)"));
            }
        }
    }
    let names: Vec<&str> = mappings.iter().map(|m| m.name.as_str()).collect();
    lines.push(format!("--   sources: {}", names.join(", ")));
    for m in mappings {
        for fm in &m.fields {
            if !fm.is_forward() {
                continue;
            }
            let tgt = fm.target.as_deref().unwrap_or("?");
            let src = fm.source.as_deref().unwrap_or("-");
            let mut parts = vec![format!("{}: {} -> {}", m.name, src, tgt)];
            if let Some(ref e) = fm.expression {
                parts.push(format!("expression: {e}"));
            }
            if let Some(p) = fm.priority {
                parts.push(format!("priority: {p}"));
            }
            lines.push(comment_lines(&format!("field: {}", parts.join(", "))));
        }
        if let Some(ref f) = m.filter {
            lines.push(comment_lines(&format!("filter ({}): {f}", m.name)));
        }
        if !m.links.is_empty() {
            for link in &m.links {
                lines.push(format!(
                    "--   link: {:?} -> references {}",
                    link.field, link.references
                ));
            }
        }
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_resolution(target: &Target) -> String {
    let mut lines = Vec::new();
    lines.push("-- [annotate] resolution strategies:".to_string());
    for (fname, fdef) in &target.fields {
        let strat = fdef.strategy();
        let strat_lower = format!("{strat:?}").to_lowercase();
        let mut parts = if strat == Strategy::Expression {
            if let Some(e) = fdef.expression() {
                vec![format!("{fname}: {e}")]
            } else {
                vec![format!("{fname}: {strat_lower}")]
            }
        } else {
            let mut p = vec![format!("{fname}: {strat_lower}")];
            if let Some(e) = fdef.expression() {
                p.push(format!("expression: {e}"));
            }
            p
        };
        if let Some(g) = fdef.group() {
            parts.push(format!("group: {g}"));
        }
        if let Some(d) = fdef.default_expression() {
            parts.push(format!("default_expression: {d}"));
        } else if let Some(d) = fdef.default_value() {
            parts.push(format!("default: {d:?}"));
        }
        lines.push(comment_lines(&parts.join(", ")));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_reverse(m: &Mapping) -> String {
    let mut lines = Vec::new();
    lines.push(format!("-- [annotate] _rev_{}: reverse projection", m.name));
    for fm in &m.fields {
        if fm.is_reverse() {
            let tgt = fm.target.as_deref().unwrap_or("?");
            let src = fm.source.as_deref().unwrap_or("-");
            let mut parts = vec![format!("{tgt} -> {src}")];
            if let Some(ref e) = fm.reverse_expression {
                parts.push(format!("reverse_expression: {e}"));
            }
            if fm.reverse_required {
                parts.push("reverse_required".to_string());
            }
            lines.push(comment_lines(&format!("field: {}", parts.join(", "))));
        }
    }
    if let Some(ref rf) = m.reverse_filter {
        lines.push(comment_lines(&format!("reverse_filter: {rf}")));
    }
    lines.push(String::new());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dag::build_dag;
    use crate::parser;

    fn parse(yaml: &str) -> crate::model::MappingDocument {
        parser::parse_str(yaml).expect("valid test YAML")
    }

    #[test]
    fn osi_text_norm_function() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  order: { fields: { oid: { strategy: identity } } }
  line: { fields: { lid: { strategy: identity }, oref: { strategy: coalesce, references: order } } }
mappings:
  - name: s_orders
    source: s
    target: order
    fields: [{ source: id, target: oid }]
  - name: s_lines
    parent: s_orders
    array: lines
    parent_fields: { pid: id }
    target: line
    fields:
      - { source: lid, target: lid }
      - { source: pid, target: oref, references: s_orders }
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, false).unwrap();
        assert!(
            sql.contains("CREATE OR REPLACE FUNCTION _osi_text_norm"),
            "nested arrays should emit _osi_text_norm helper function"
        );
    }

    #[test]
    fn view_order_follows_dag() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, false).unwrap();
        let fwd_pos = sql.find("_fwd_s").expect("should contain forward view");
        let id_pos = sql.find("_id_t").expect("should contain identity view");
        let res_pos = sql
            .find("_resolved_t")
            .expect("should contain resolution view");
        let delta_pos = sql.find("_delta_s").expect("should contain delta view");
        assert!(fwd_pos < id_pos, "forward should come before identity");
        assert!(id_pos < res_pos, "identity should come before resolution");
        assert!(res_pos < delta_pos, "resolution should come before delta");
    }

    #[test]
    fn create_tables_ddl() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  my_source: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: my_source
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, true, false, false).unwrap();
        assert!(
            sql.contains("CREATE TABLE") && sql.contains("my_source"),
            "--create-tables should emit CREATE TABLE for source"
        );
    }

    #[test]
    fn create_tables_infers_types_from_tests() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  src:
    primary_key: id
    fields:
      explicit_col: { type: numeric }
targets:
  t:
    fields:
      name: { strategy: coalesce }
      age: { strategy: coalesce }
      active: { strategy: coalesce }
      score: { strategy: coalesce }
      tags: { strategy: coalesce }
      explicit_col: { strategy: coalesce }
mappings:
  - name: m
    source: src
    target: t
    fields:
      - { source: name, target: name }
      - { source: age, target: age }
      - { source: active, target: active }
      - { source: score, target: score }
      - { source: tags, target: tags }
      - { source: explicit_col, target: explicit_col }
tests:
  - description: type inference
    input:
      src:
        - { id: "1", name: "Alice", age: 30, active: true, score: 9.5, tags: ["a", "b"], explicit_col: "x" }
        - { id: "2", name: "Bob", age: 25, active: false, score: 8.0, tags: ["c"], explicit_col: "y" }
    expected: {}
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, true, false, false).unwrap();

        // String columns → TEXT
        assert!(sql.contains("\"name\" TEXT"), "string → TEXT:\n{sql}");
        // Integer columns → BIGINT
        assert!(sql.contains("\"age\" BIGINT"), "integer → BIGINT:\n{sql}");
        // Boolean columns → BOOLEAN
        assert!(sql.contains("\"active\" BOOLEAN"), "bool → BOOLEAN:\n{sql}");
        // Float columns → DOUBLE PRECISION
        assert!(
            sql.contains("\"score\" DOUBLE PRECISION"),
            "float → DOUBLE PRECISION:\n{sql}"
        );
        // Array columns → JSONB
        assert!(sql.contains("\"tags\" JSONB"), "array → JSONB:\n{sql}");
        // Explicit type beats inference
        assert!(
            sql.contains("\"explicit_col\" numeric"),
            "explicit type declaration should override inference:\n{sql}"
        );
    }

    #[test]
    fn create_tables_mixed_types_fall_back_to_text() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  src: { primary_key: id }
targets:
  t: { fields: { val: { strategy: coalesce } } }
mappings:
  - name: m
    source: src
    target: t
    fields: [{ source: val, target: val }]
tests:
  - description: mixed types
    input:
      src:
        - { id: "1", val: 42 }
        - { id: "2", val: "text" }
    expected: {}
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, true, false, false).unwrap();
        assert!(
            sql.contains("\"val\" TEXT"),
            "mixed types should fall back to TEXT:\n{sql}"
        );
    }

    #[test]
    fn annotate_comments() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, true, false).unwrap();
        assert!(
            sql.contains("-- [fwd]")
                || sql.contains("-- Forward:")
                || sql.contains("-- Annotation"),
            "--annotate should emit comment blocks before views"
        );
    }

    #[test]
    fn multiline_expression_fully_commented() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t:
    fields:
      tid: { strategy: identity }
      computed:
        strategy: expression
        expression: |
          COALESCE((
            SELECT count(*)
            FROM other_table o
            WHERE o.ref = t.tid
          ), 0)
        type: numeric
mappings:
  - name: s
    source: s
    target: t
    fields:
      - { source: id, target: tid }
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, true, false).unwrap();
        // Every line in the resolution annotation block must be a SQL comment.
        let annotation_block: Vec<&str> = sql
            .lines()
            .skip_while(|l| !l.contains("[annotate] resolution"))
            .take_while(|l| l.starts_with("--"))
            .collect();
        assert!(
            annotation_block.len() > 2,
            "multi-line expression should produce multiple annotation lines"
        );
        for line in &annotation_block {
            assert!(
                line.starts_with("--"),
                "annotation line not commented: {line}"
            );
        }
    }

    #[test]
    fn materialize_emits_materialized_views() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        assert!(
            sql.contains("CREATE MATERIALIZED VIEW IF NOT EXISTS"),
            "materialize should emit MATERIALIZED VIEW"
        );
        assert!(
            !sql.contains("CREATE OR REPLACE VIEW"),
            "materialize should not emit plain VIEW"
        );
    }

    #[test]
    fn materialize_emits_unique_indexes() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        // Forward view: unique on _src_id
        assert!(
            sql.contains("idx__fwd_s") && sql.contains("\"_src_id\""),
            "forward view should have unique index on _src_id"
        );
        // Identity view: unique on _entity_id
        assert!(
            sql.contains("idx__id_t") && sql.contains("\"_entity_id\""),
            "identity view should have unique index on _entity_id"
        );
        // Analytics view: unique on _cluster_id
        assert!(
            sql.contains("idx_t") && sql.contains("\"_cluster_id\""),
            "analytics view should have unique index on _cluster_id"
        );
        // Delta view: unique on (_cluster_id, pk) with NULLS NOT DISTINCT
        assert!(
            sql.contains("idx__delta_s") && sql.contains("NULLS NOT DISTINCT"),
            "delta view should have unique index with NULLS NOT DISTINCT"
        );
    }

    #[test]
    fn materialize_emits_refresh_script() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        assert!(
            sql.contains("REFRESH MATERIALIZED VIEW CONCURRENTLY"),
            "materialize should emit refresh script"
        );
        // Refresh order should follow DAG
        let fwd_refresh = sql
            .find("REFRESH MATERIALIZED VIEW CONCURRENTLY \"_fwd_s\"")
            .expect("missing fwd refresh");
        let id_refresh = sql
            .find("REFRESH MATERIALIZED VIEW CONCURRENTLY \"_id_t\"")
            .expect("missing id refresh");
        let res_refresh = sql
            .find("REFRESH MATERIALIZED VIEW CONCURRENTLY \"_resolved_t\"")
            .expect("missing resolved refresh");
        assert!(
            fwd_refresh < id_refresh && id_refresh < res_refresh,
            "refresh order should follow DAG"
        );
    }

    #[test]
    fn materialize_delta_composite_pk() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: [order_id, line_no] }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        // Delta index should include all PK columns
        assert!(
            sql.contains("\"order_id\"") && sql.contains("\"line_no\""),
            "delta index should include composite PK columns"
        );
    }

    #[test]
    fn non_materialize_has_no_indexes() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, false).unwrap();
        assert!(
            !sql.contains("CREATE UNIQUE INDEX"),
            "non-materialize should not emit indexes"
        );
        assert!(
            !sql.contains("REFRESH MATERIALIZED"),
            "non-materialize should not emit refresh"
        );
    }

    #[test]
    fn array_forward_index_includes_identity_fields() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  parent_src: { primary_key: id }
targets:
  parent_t:
    fields:
      pid: { strategy: identity }
      name: { strategy: coalesce }
  child_t:
    fields:
      cid: { strategy: identity, type: numeric }
      amount: { strategy: last_modified, type: numeric }
      parent_ref: { strategy: coalesce, references: parent_t }
mappings:
  - name: parent_map
    source: parent_src
    target: parent_t
    last_modified: updated_at
    fields:
      - { source: id, target: pid }
      - { source: name, target: name }
  - name: child_map
    parent: parent_map
    array: items
    target: child_t
    last_modified: updated_at
    parent_fields:
      parent_id: id
    fields:
      - { source: cid, target: cid }
      - { source: amount, target: amount }
      - { source: parent_id, target: parent_ref }
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        // The array-expanded forward view must include identity column(s) in
        // the unique index — _src_id alone is not unique after array expansion.
        let child_idx = sql
            .lines()
            .find(|l| l.contains("_fwd_child_map") && l.trim_start().starts_with("ON"))
            .expect("missing ON clause for array forward view index");
        assert!(
            child_idx.contains("\"_src_id\"") && child_idx.contains("\"cid\""),
            "array forward index should include identity field: {child_idx}"
        );
        // Non-array parent forward view should still be _src_id only.
        let parent_idx = sql
            .lines()
            .find(|l| l.contains("_fwd_parent_map") && l.trim_start().starts_with("ON"))
            .expect("missing ON clause for parent forward view index");
        assert!(
            parent_idx.contains("\"_src_id\"") && !parent_idx.contains("\"pid\""),
            "non-array forward index should be _src_id only: {parent_idx}"
        );
    }

    #[test]
    fn array_forward_index_composite_identity() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  src: { primary_key: id }
targets:
  parent_t:
    fields:
      pid: { strategy: identity }
  child_t:
    fields:
      order_ref:
        strategy: identity
        references: parent_t
      line_number:
        strategy: identity
        type: numeric
      amount: { strategy: last_modified, type: numeric }
mappings:
  - name: parent_fwd
    source: src
    target: parent_t
    fields:
      - { source: id, target: pid }
  - name: child_fwd
    parent: parent_fwd
    array: lines
    target: child_t
    parent_fields:
      parent_id: id
    fields:
      - { source: parent_id, target: order_ref }
      - { source: line_no, target: line_number }
      - { source: amount, target: amount }
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        // Composite identity: both identity fields must appear in the index.
        let idx_line = sql
            .lines()
            .find(|l| l.contains("_fwd_child_fwd") && l.trim_start().starts_with("ON"))
            .expect("missing ON clause for composite-identity array forward view index");
        assert!(
            idx_line.contains("\"order_ref\"") && idx_line.contains("\"line_number\""),
            "composite identity fields should both be in array forward index: {idx_line}"
        );
    }
}
