pub mod analytics;
pub mod delta;
pub mod enriched;
pub mod forward;
pub mod identity;
pub mod ordered;
pub mod resolution;
pub mod reverse;

use anyhow::Result;

use crate::dag::{ViewDag, ViewNode};
use crate::model::MappingDocument;

/// Replace `CREATE OR REPLACE VIEW` with `CREATE MATERIALIZED VIEW IF NOT EXISTS`
/// in the generated SQL for a single view.
fn materialize_view_sql(view_sql: &str) -> String {
    view_sql.replace(
        "CREATE OR REPLACE VIEW",
        "CREATE MATERIALIZED VIEW IF NOT EXISTS",
    )
}

/// Emit a `CREATE UNIQUE INDEX IF NOT EXISTS` statement for a view.
///
/// `nulls_not_distinct` should be true when the key may contain NULL columns
/// (reverse and delta views where insert rows have NULL PKs).
fn emit_unique_index(view_name: &str, columns: &[&str], nulls_not_distinct: bool) -> String {
    let qi_view = crate::qi(view_name);
    let idx_name = crate::qi(&format!("idx_{view_name}"));
    let cols = columns
        .iter()
        .map(|c| crate::qi(c))
        .collect::<Vec<_>>()
        .join(", ");
    let nulls_clause = if nulls_not_distinct {
        "\n  NULLS NOT DISTINCT"
    } else {
        ""
    };
    format!(
        "CREATE UNIQUE INDEX IF NOT EXISTS {idx_name}\n  ON {qi_view} ({cols}){nulls_clause};\n"
    )
}

/// Render the complete SQL script for a mapping document.
///
/// When `create_tables` is true, emits `CREATE TABLE` statements for all
/// input tables (source datasets and cluster_members tables) so the output
/// is self-contained and can be executed in an empty Postgres database.
///
/// When `annotate` is true, emits inline comments before each view showing
/// which user-defined expressions, filters, and strategies drove the SQL.
///
/// When `materialize` is true, emits `CREATE MATERIALIZED VIEW IF NOT EXISTS`
/// instead of `CREATE OR REPLACE VIEW`, adds unique indexes per view, and
/// appends a `REFRESH MATERIALIZED VIEW CONCURRENTLY` script.
pub fn render_sql(
    doc: &MappingDocument,
    dag: &ViewDag,
    create_tables: bool,
    annotate: bool,
    materialize: bool,
) -> Result<String> {
    let mut sql = String::new();

    sql.push_str("-- Generated by osi-engine — OSI mapping reference engine\n");
    sql.push_str("-- Do not edit manually.\n\n");
    sql.push_str("BEGIN;\n\n");

    // Emit JSONB text-normalization helper when nested arrays are present.
    // This function recursively converts all scalar values to text/string
    // so noop detection can compare original JSONB (which may have native
    // integer/boolean types) against reconstructed JSONB (always text).
    let has_nested = doc.mappings.iter().any(|m| m.source.path.is_some());
    if has_nested {
        sql.push_str(
            "CREATE OR REPLACE FUNCTION _osi_text_norm(j jsonb) RETURNS jsonb\n\
             LANGUAGE plpgsql IMMUTABLE AS $$\n\
             BEGIN\n  \
               IF j IS NULL THEN RETURN NULL; END IF;\n  \
               CASE jsonb_typeof(j)\n    \
                 WHEN 'array' THEN\n      \
                   RETURN COALESCE(\n        \
                     (SELECT jsonb_agg(_osi_text_norm(elem) ORDER BY idx)\n         \
                      FROM jsonb_array_elements(j) WITH ORDINALITY AS t(elem, idx)),\n        \
                     '[]'::jsonb);\n    \
                 WHEN 'object' THEN\n      \
                   RETURN COALESCE(\n        \
                     (SELECT jsonb_object_agg(key, _osi_text_norm(value))\n         \
                      FROM jsonb_each(j)),\n        \
                     '{}'::jsonb);\n    \
                 WHEN 'null' THEN RETURN 'null'::jsonb;\n    \
                 ELSE RETURN to_jsonb(j #>> '{}');\n  \
               END CASE;\n\
             END;\n\
             $$;\n\n",
        );
    }

    // Track materialized view names for the refresh script.
    let mut mat_view_names: Vec<String> = Vec::new();

    for node in &dag.order {
        match node {
            ViewNode::Source(table_name) => {
                if create_tables {
                    sql.push_str(&render_input_table(doc, table_name));
                    sql.push('\n');
                }
            }
            ViewNode::Forward(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                let target_name = mapping.target.name();
                let target = doc.targets.get(target_name);
                let source_meta = doc.sources.get(&mapping.source.dataset);
                if annotate {
                    sql.push_str(&annotate_forward(mapping, target));
                }
                let nested_base_cols: Vec<String> = if mapping.source.path.is_none() {
                    let mut cols: Vec<String> = Vec::new();
                    for m in &doc.mappings {
                        if m.source.dataset == mapping.source.dataset && m.source.path.is_some() {
                            if let Some(ref p) = m.source.path {
                                let root = p.split('.').next().unwrap_or(p).to_string();
                                if !cols.contains(&root) {
                                    cols.push(root);
                                }
                            }
                        }
                    }
                    cols
                } else {
                    vec![]
                };
                // Collect canonical normalize expressions across all mappings
                // targeting the same entity so forward views emit consistent
                // _normalize columns for echo-aware resolution (Phase 2).
                let normalize_fields: std::collections::HashMap<String, String> = {
                    let mut map = std::collections::HashMap::new();
                    for m in &doc.mappings {
                        if m.target.name() == target_name {
                            for fm in &m.fields {
                                if let (Some(ref tgt), Some(ref norm)) = (&fm.target, &fm.normalize)
                                {
                                    map.entry(tgt.clone()).or_insert_with(|| norm.clone());
                                }
                            }
                        }
                    }
                    map
                };
                let mut view_sql = forward::render_forward_view(
                    mapping,
                    source_meta,
                    target,
                    &nested_base_cols,
                    &normalize_fields,
                    &doc.mappings,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_src_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Identity(target_name) => {
                let target = doc.targets.get(target_name);
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                if annotate {
                    sql.push_str(&annotate_identity(&mappings, target));
                }
                let fwd_names: Vec<String> = mappings
                    .iter()
                    .filter(|m| m.has_fields())
                    .map(|m| m.name.clone())
                    .collect();
                let mut view_sql = identity::render_identity_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.mappings,
                    &doc.sources,
                    &fwd_names,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_entity_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Resolved(target_name) => {
                let target = doc.targets.get(target_name).expect("target exists in dag");
                if annotate {
                    sql.push_str(&annotate_resolution(target));
                }
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                let mut view_sql = resolution::render_resolution_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.targets,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_entity_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Ordered(target_name) => {
                let target = doc.targets.get(target_name).expect("target exists in dag");
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                let mut view_sql = ordered::render_ordered_view(target_name, target, &mappings)?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_entity_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Analytics(target_name) => {
                let target = doc.targets.get(target_name).expect("target exists in dag");
                let has_enriched = dag
                    .edges
                    .contains_key(&ViewNode::Enriched(target_name.clone()));
                let mut view_sql =
                    analytics::render_analytics_view(target_name, target, has_enriched)?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_cluster_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Enriched(target_name) => {
                let target = doc.targets.get(target_name).expect("target exists in dag");
                let all_target_names: Vec<&str> = doc.targets.keys().map(|s| s.as_str()).collect();
                let has_mixed_order = dag
                    .edges
                    .contains_key(&ViewNode::Ordered(target_name.clone()));
                let mut view_sql = enriched::render_enriched_view(
                    target_name,
                    target,
                    &all_target_names,
                    has_mixed_order,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_entity_id"], false));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Reverse(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                if annotate {
                    sql.push_str(&annotate_reverse(mapping));
                }
                let target_name = mapping.target.name();
                let target = doc.targets.get(target_name);
                let source_meta = doc.sources.get(&mapping.source.dataset);
                let has_enriched = dag
                    .edges
                    .contains_key(&ViewNode::Enriched(target_name.to_string()));
                let mut view_sql = reverse::render_reverse_view(
                    mapping,
                    target_name,
                    target,
                    &doc.targets,
                    source_meta,
                    &doc.mappings,
                    &doc.sources,
                    has_enriched,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    view_sql.push_str(&emit_unique_index(&vn, &["_cluster_id", "_src_id"], true));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
            ViewNode::Delta(source_name) => {
                let source_mappings: Vec<&_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.source.dataset == *source_name && m.needs_sync())
                    .collect();
                if annotate {
                    sql.push_str(&format!("-- Delta for source: {source_name}\n"));
                }
                let source_meta = doc.sources.get(source_name.as_str());
                let mut view_sql = delta::render_delta_view(
                    source_name,
                    &source_mappings,
                    source_meta,
                    &doc.targets,
                    &doc.mappings,
                )?;
                if materialize {
                    view_sql = materialize_view_sql(&view_sql);
                    let vn = node.view_name();
                    let mut key_cols: Vec<&str> = vec!["_cluster_id"];
                    if let Some(src) = source_meta {
                        for col in src.primary_key.columns() {
                            key_cols.push(col);
                        }
                    }
                    view_sql.push_str(&emit_unique_index(&vn, &key_cols, true));
                    mat_view_names.push(vn);
                }
                sql.push_str(&view_sql);
                sql.push('\n');
            }
        }
    }

    // Emit refresh script when materializing.
    if materialize && !mat_view_names.is_empty() {
        sql.push_str("-- Refresh materialized views in dependency order\n");
        for vn in &mat_view_names {
            sql.push_str(&format!(
                "REFRESH MATERIALIZED VIEW CONCURRENTLY {};\n",
                crate::qi(vn)
            ));
        }
        sql.push('\n');
    }

    sql.push_str("COMMIT;\n");

    Ok(sql)
}

/// Render a CREATE TABLE statement for an input table.
///
/// For source datasets: emits `_row_id SERIAL` + PK columns + all source
/// columns referenced by field mappings + timestamp columns.
///
/// For cluster_members tables: emits the cluster_id and source_key columns.
///
/// All columns are typed TEXT (the actual types depend on the source system
/// and are not declared in the mapping YAML).
fn render_input_table(doc: &MappingDocument, table_name: &str) -> String {
    use crate::qi;
    // Check if this is a cluster_members table
    for mapping in &doc.mappings {
        if let Some(ref cm) = mapping.cluster_members {
            if cm.table_name(&mapping.name) == table_name {
                return format!(
                    "-- Input table: {table_name} (cluster members)\n\
                     CREATE TABLE IF NOT EXISTS {} (\n  \
                                             {} TEXT PRIMARY KEY,\n  \
                                             {} TEXT\n\
                     );\n",
                    qi(table_name),
                    qi(&cm.source_key),
                    qi(&cm.cluster_id)
                );
            }
        }
    }

    // Check if this is a written_state table
    for mapping in &doc.mappings {
        if let Some(ref ws) = mapping.written_state {
            if ws.table_name(&mapping.name) == table_name {
                return format!(
                    "-- Input table: {table_name} (written state)\n\
                     CREATE TABLE IF NOT EXISTS {} (\n  \
                                             {} TEXT PRIMARY KEY,\n  \
                                             {} JSONB NOT NULL,\n  \
                                             {} TIMESTAMPTZ NOT NULL DEFAULT now(),\n  \
                                             {} JSONB NOT NULL DEFAULT '{{}}'::jsonb\n\
                     );\n",
                    qi(table_name),
                    qi(&ws.cluster_id),
                    qi(&ws.written),
                    qi(&ws.written_at),
                    qi(&ws.written_ts),
                );
            }
        }
    }

    // Source dataset table — collect all referenced columns.
    let mut columns: Vec<String> = Vec::new();

    // Resolve source metadata by key or by explicit table override.
    let source_meta = doc.sources.get(table_name).or_else(|| {
        doc.sources
            .iter()
            .find(|(key, src)| src.table_name(key) == table_name)
            .map(|(_key, src)| src)
    });

    // Add PK columns first so they are always present in generated DDL.
    let pk_columns: Vec<String> = source_meta
        .map(|source| {
            source
                .primary_key
                .columns()
                .into_iter()
                .map(|c| c.to_string())
                .collect()
        })
        .unwrap_or_default();
    for col in &pk_columns {
        if !columns.contains(col) {
            columns.push(col.clone());
        }
    }

    // Scan all mappings that use this source dataset
    let mut jsonb_cols: std::collections::HashSet<String> = std::collections::HashSet::new();
    for mapping in &doc.mappings {
        let src_table = doc
            .sources
            .get(&mapping.source.dataset)
            .map(|s| s.table_name(&mapping.source.dataset).to_string())
            .unwrap_or_else(|| mapping.source.dataset.clone());
        if src_table != table_name {
            continue;
        }

        // Field source columns
        for fm in &mapping.fields {
            if let Some(ref _sp) = fm.source_path {
                // source_path: physical column is first segment, typed JSONB.
                if let Some(col) = fm.source_column() {
                    if !columns.contains(&col.to_string()) {
                        columns.push(col.to_string());
                    }
                    jsonb_cols.insert(col.to_string());
                }
            } else if let Some(ref src) = fm.source {
                if !columns.contains(src) {
                    columns.push(src.clone());
                }
            }
            // Per-field last_modified column
            if let Some(ref ts) = fm.last_modified {
                if let Some(field) = ts.field_name() {
                    let f = field.to_string();
                    if !columns.contains(&f) {
                        columns.push(f);
                    }
                }
            }
        }

        // Mapping-level last_modified column
        if let Some(ref ts) = mapping.last_modified {
            if let Some(field) = ts.field_name() {
                let f = field.to_string();
                if !columns.contains(&f) {
                    columns.push(f);
                }
            }
        }

        // cluster_field column
        if let Some(ref cf) = mapping.cluster_field {
            if !columns.contains(cf) {
                columns.push(cf.clone());
            }
        }

        // passthrough columns
        for col in &mapping.passthrough {
            if !columns.contains(col) {
                columns.push(col.clone());
            }
        }
    }

    let mut col_defs: Vec<String> = Vec::new();
    if pk_columns.is_empty() {
        // Fallback for mappings without declared source PK metadata.
        col_defs.push("_row_id SERIAL PRIMARY KEY".to_string());
    }
    col_defs.extend(columns.iter().map(|c| {
        if jsonb_cols.contains(c) {
            format!("{} JSONB", qi(c))
        } else {
            format!("{} TEXT", qi(c))
        }
    }));
    if !pk_columns.is_empty() {
        col_defs.push(format!(
            "PRIMARY KEY ({})",
            pk_columns
                .iter()
                .map(|c| qi(c))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    format!(
        "-- Input table: {table_name}\n\
         CREATE TABLE IF NOT EXISTS {} (\n  {}\n);\n",
        qi(table_name),
        col_defs.join(",\n  ")
    )
}

// ---------------------------------------------------------------------------
// Annotation helpers — emit SQL comments showing user-defined configuration
// ---------------------------------------------------------------------------

use crate::model::{Mapping, Strategy, Target};

fn annotate_forward(m: &Mapping, _target: Option<&Target>) -> String {
    let mut lines = Vec::new();
    lines.push(format!(
        "-- [annotate] _fwd_{}: {} -> {}",
        m.name,
        m.source.dataset,
        m.target.name()
    ));
    for fm in &m.fields {
        if !fm.is_forward() {
            continue;
        }
        let tgt = fm.target.as_deref().unwrap_or("?");
        let src = fm.source.as_deref().unwrap_or("-");
        if let Some(ref e) = fm.expression {
            lines.push(format!("--   {src} -> {tgt} (expression: {e})"));
        } else {
            lines.push(format!("--   {src} -> {tgt}"));
        }
    }
    if let Some(ref f) = m.filter {
        lines.push(format!("--   filter: {f}"));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_identity(mappings: &[&Mapping], target: Option<&Target>) -> String {
    let mut lines = Vec::new();
    let target_name = mappings.first().map(|m| m.target.name()).unwrap_or("?");
    lines.push(format!("-- [annotate] _id_{target_name}: identity fields"));
    if let Some(t) = target {
        for (fname, fdef) in &t.fields {
            if fdef.strategy() == Strategy::Identity {
                lines.push(format!("--   {fname} (identity)"));
            }
        }
    }
    let names: Vec<&str> = mappings.iter().map(|m| m.name.as_str()).collect();
    lines.push(format!("--   sources: {}", names.join(", ")));
    for m in mappings {
        for fm in &m.fields {
            if !fm.is_forward() {
                continue;
            }
            let tgt = fm.target.as_deref().unwrap_or("?");
            let src = fm.source.as_deref().unwrap_or("-");
            let mut parts = vec![format!("{}: {} -> {}", m.name, src, tgt)];
            if let Some(ref e) = fm.expression {
                parts.push(format!("expression: {e}"));
            }
            if let Some(p) = fm.priority {
                parts.push(format!("priority: {p}"));
            }
            lines.push(format!("--   field: {}", parts.join(", ")));
        }
        if let Some(ref f) = m.filter {
            lines.push(format!("--   filter ({}): {f}", m.name));
        }
        if !m.links.is_empty() {
            for link in &m.links {
                lines.push(format!(
                    "--   link: {:?} -> references {}",
                    link.field, link.references
                ));
            }
        }
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_resolution(target: &Target) -> String {
    let mut lines = Vec::new();
    lines.push("-- [annotate] resolution strategies:".to_string());
    for (fname, fdef) in &target.fields {
        let strat = format!("{:?}", fdef.strategy()).to_lowercase();
        let mut parts = vec![format!("{fname}: {strat}")];
        if let Some(e) = fdef.expression() {
            parts.push(format!("expression: {e}"));
        }
        if let Some(g) = fdef.group() {
            parts.push(format!("group: {g}"));
        }
        if let Some(d) = fdef.default_expression() {
            parts.push(format!("default_expression: {d}"));
        } else if let Some(d) = fdef.default_value() {
            parts.push(format!("default: {d:?}"));
        }
        lines.push(format!("--   {}", parts.join(", ")));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_reverse(m: &Mapping) -> String {
    let mut lines = Vec::new();
    lines.push(format!("-- [annotate] _rev_{}: reverse projection", m.name));
    for fm in &m.fields {
        if fm.is_reverse() {
            let tgt = fm.target.as_deref().unwrap_or("?");
            let src = fm.source.as_deref().unwrap_or("-");
            let mut parts = vec![format!("{tgt} -> {src}")];
            if let Some(ref e) = fm.reverse_expression {
                parts.push(format!("reverse_expression: {e}"));
            }
            if fm.reverse_required {
                parts.push("reverse_required".to_string());
            }
            lines.push(format!("--   field: {}", parts.join(", ")));
        }
    }
    if let Some(ref rf) = m.reverse_filter {
        lines.push(format!("--   reverse_filter: {rf}"));
    }
    lines.push(String::new());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dag::build_dag;
    use crate::parser;

    fn parse(yaml: &str) -> crate::model::MappingDocument {
        parser::parse_str(yaml).expect("valid test YAML")
    }

    #[test]
    fn osi_text_norm_function() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  order: { fields: { oid: { strategy: identity } } }
  line: { fields: { lid: { strategy: identity }, oref: { strategy: coalesce, references: order } } }
mappings:
  - name: s_orders
    source: s
    target: order
    fields: [{ source: id, target: oid }]
  - name: s_lines
    parent: s_orders
    array: lines
    parent_fields: { pid: id }
    target: line
    fields:
      - { source: lid, target: lid }
      - { source: pid, target: oref, references: s_orders }
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, false).unwrap();
        assert!(
            sql.contains("CREATE OR REPLACE FUNCTION _osi_text_norm"),
            "nested arrays should emit _osi_text_norm helper function"
        );
    }

    #[test]
    fn view_order_follows_dag() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, false).unwrap();
        let fwd_pos = sql.find("_fwd_s").expect("should contain forward view");
        let id_pos = sql.find("_id_t").expect("should contain identity view");
        let res_pos = sql
            .find("_resolved_t")
            .expect("should contain resolution view");
        let delta_pos = sql.find("_delta_s").expect("should contain delta view");
        assert!(fwd_pos < id_pos, "forward should come before identity");
        assert!(id_pos < res_pos, "identity should come before resolution");
        assert!(res_pos < delta_pos, "resolution should come before delta");
    }

    #[test]
    fn create_tables_ddl() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  my_source: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: my_source
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, true, false, false).unwrap();
        assert!(
            sql.contains("CREATE TABLE") && sql.contains("my_source"),
            "--create-tables should emit CREATE TABLE for source"
        );
    }

    #[test]
    fn annotate_comments() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, true, false).unwrap();
        assert!(
            sql.contains("-- [fwd]")
                || sql.contains("-- Forward:")
                || sql.contains("-- Annotation"),
            "--annotate should emit comment blocks before views"
        );
    }

    #[test]
    fn materialize_emits_materialized_views() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        assert!(
            sql.contains("CREATE MATERIALIZED VIEW IF NOT EXISTS"),
            "materialize should emit MATERIALIZED VIEW"
        );
        assert!(
            !sql.contains("CREATE OR REPLACE VIEW"),
            "materialize should not emit plain VIEW"
        );
    }

    #[test]
    fn materialize_emits_unique_indexes() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        // Forward view: unique on _src_id
        assert!(
            sql.contains("idx__fwd_s") && sql.contains("\"_src_id\""),
            "forward view should have unique index on _src_id"
        );
        // Identity view: unique on _entity_id
        assert!(
            sql.contains("idx__id_t") && sql.contains("\"_entity_id\""),
            "identity view should have unique index on _entity_id"
        );
        // Analytics view: unique on _cluster_id
        assert!(
            sql.contains("idx_t") && sql.contains("\"_cluster_id\""),
            "analytics view should have unique index on _cluster_id"
        );
        // Delta view: unique on (_cluster_id, pk) with NULLS NOT DISTINCT
        assert!(
            sql.contains("idx__delta_s") && sql.contains("NULLS NOT DISTINCT"),
            "delta view should have unique index with NULLS NOT DISTINCT"
        );
    }

    #[test]
    fn materialize_emits_refresh_script() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        assert!(
            sql.contains("REFRESH MATERIALIZED VIEW CONCURRENTLY"),
            "materialize should emit refresh script"
        );
        // Refresh order should follow DAG
        let fwd_refresh = sql
            .find("REFRESH MATERIALIZED VIEW CONCURRENTLY \"_fwd_s\"")
            .expect("missing fwd refresh");
        let id_refresh = sql
            .find("REFRESH MATERIALIZED VIEW CONCURRENTLY \"_id_t\"")
            .expect("missing id refresh");
        let res_refresh = sql
            .find("REFRESH MATERIALIZED VIEW CONCURRENTLY \"_resolved_t\"")
            .expect("missing resolved refresh");
        assert!(
            fwd_refresh < id_refresh && id_refresh < res_refresh,
            "refresh order should follow DAG"
        );
    }

    #[test]
    fn materialize_delta_composite_pk() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: [order_id, line_no] }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, true).unwrap();
        // Delta index should include all PK columns
        assert!(
            sql.contains("\"order_id\"") && sql.contains("\"line_no\""),
            "delta index should include composite PK columns"
        );
    }

    #[test]
    fn non_materialize_has_no_indexes() {
        let doc = parse(
            r#"
version: "1.0"
sources:
  s: { primary_key: id }
targets:
  t: { fields: { name: { strategy: coalesce } } }
mappings:
  - name: s
    source: s
    target: t
    fields: [{ source: name, target: name }]
"#,
        );
        let dag = build_dag(&doc);
        let sql = render_sql(&doc, &dag, false, false, false).unwrap();
        assert!(
            !sql.contains("CREATE UNIQUE INDEX"),
            "non-materialize should not emit indexes"
        );
        assert!(
            !sql.contains("REFRESH MATERIALIZED"),
            "non-materialize should not emit refresh"
        );
    }
}
