pub mod forward;
pub mod identity;
pub mod resolution;
pub mod reverse;
pub mod delta;
pub mod analytics;

use anyhow::Result;

use crate::dag::{ViewDag, ViewNode};
use crate::model::MappingDocument;

/// Render the complete SQL script for a mapping document.
///
/// When `create_tables` is true, emits `CREATE TABLE` statements for all
/// input tables (source datasets and cluster_members tables) so the output
/// is self-contained and can be executed in an empty Postgres database.
///
/// When `annotate` is true, emits inline comments before each view showing
/// which user-defined expressions, filters, and strategies drove the SQL.
pub fn render_sql(doc: &MappingDocument, dag: &ViewDag, create_tables: bool, annotate: bool) -> Result<String> {
    let mut sql = String::new();

    sql.push_str("-- Generated by osi-engine — OSI mapping reference engine\n");
    sql.push_str("-- Do not edit manually.\n\n");
    sql.push_str("BEGIN;\n\n");

    for node in &dag.order {
        match node {
            ViewNode::Source(table_name) => {
                if create_tables {
                    sql.push_str(&render_input_table(doc, table_name));
                    sql.push('\n');
                }
            }
            ViewNode::Forward(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                let target_name = mapping.target.name();
                let target = doc.targets.get(target_name);
                let source_meta = doc.sources.get(&mapping.source.dataset);
                if annotate {
                    sql.push_str(&annotate_forward(mapping, target));
                }
                // Collect nested-path source columns from sibling mappings
                // so the parent's _base includes them for noop detection.
                let nested_base_cols: Vec<String> = if mapping.source.path.is_none() {
                    let mut cols: Vec<String> = Vec::new();
                    for m in &doc.mappings {
                        if m.source.dataset == mapping.source.dataset && m.source.path.is_some() {
                            if let Some(ref p) = m.source.path {
                                let root = p.split('.').next().unwrap_or(p).to_string();
                                if !cols.contains(&root) {
                                    cols.push(root);
                                }
                            }
                        }
                    }
                    cols
                } else {
                    vec![]
                };
                sql.push_str(&forward::render_forward_view(mapping, source_meta, target, &nested_base_cols)?);
                sql.push('\n');
            }
            ViewNode::Identity(target_name) => {
                let target = doc.targets.get(target_name);
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                if annotate {
                    sql.push_str(&annotate_identity(&mappings, target));
                }
                // Collect forward view names (mapping names that have fields).
                let fwd_names: Vec<String> = mappings
                    .iter()
                    .filter(|m| m.has_fields())
                    .map(|m| m.name.clone())
                    .collect();
                sql.push_str(&identity::render_identity_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.mappings,
                    &doc.sources,
                    &fwd_names,
                )?);
                sql.push('\n');
            }
            ViewNode::Resolved(target_name) => {
                let target = doc
                    .targets
                    .get(target_name)
                    .expect("target exists in dag");
                if annotate {
                    sql.push_str(&annotate_resolution(target));
                }
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                sql.push_str(&resolution::render_resolution_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.targets,
                )?);
                sql.push('\n');
            }
            ViewNode::Analytics(target_name) => {
                let target = doc
                    .targets
                    .get(target_name)
                    .expect("target exists in dag");
                sql.push_str(&analytics::render_analytics_view(target_name, target)?);
                sql.push('\n');
            }
            ViewNode::Reverse(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                if annotate {
                    sql.push_str(&annotate_reverse(mapping));
                }
                let target_name = mapping.target.name();
                let target = doc.targets.get(target_name);
                let source_meta = doc.sources.get(&mapping.source.dataset);
                sql.push_str(&reverse::render_reverse_view(
                    mapping,
                    target_name,
                    target,
                    &doc.targets,
                    source_meta,
                )?);
                sql.push('\n');
            }
            ViewNode::Delta(source_name) => {
                let source_mappings: Vec<&_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.source.dataset == *source_name && m.needs_sync())
                    .collect();
                if annotate {
                    sql.push_str(&format!("-- Delta for source: {source_name}\n"));
                }
                let source_meta = doc.sources.get(source_name.as_str());
                sql.push_str(&delta::render_delta_view(source_name, &source_mappings, source_meta)?);
                sql.push('\n');
            }
        }
    }

    sql.push_str("COMMIT;\n");

    Ok(sql)
}

/// Render a CREATE TABLE statement for an input table.
///
/// For source datasets: emits `_row_id SERIAL` + PK columns + all source
/// columns referenced by field mappings + timestamp columns.
///
/// For cluster_members tables: emits the cluster_id and source_key columns.
///
/// All columns are typed TEXT (the actual types depend on the source system
/// and are not declared in the mapping YAML).
fn render_input_table(doc: &MappingDocument, table_name: &str) -> String {
    use crate::qi;
    // Check if this is a cluster_members table
    for mapping in &doc.mappings {
        if let Some(ref cm) = mapping.cluster_members {
            if cm.table_name(&mapping.name) == table_name {
                return format!(
                    "-- Input table: {table_name} (cluster members)\n\
                     CREATE TABLE IF NOT EXISTS {} (\n  \
                                             {} TEXT PRIMARY KEY,\n  \
                                             {} TEXT\n\
                     );\n",
                    qi(table_name), qi(&cm.source_key), qi(&cm.cluster_id)
                );
            }
        }
    }

    // Source dataset table — collect all referenced columns.
    let mut columns: Vec<String> = Vec::new();

    // Resolve source metadata by key or by explicit table override.
    let source_meta = doc
        .sources
        .get(table_name)
        .or_else(|| {
            doc.sources
                .iter()
                .find(|(key, src)| src.table_name(key) == table_name)
                .map(|(_key, src)| src)
        });

    // Add PK columns first so they are always present in generated DDL.
    let pk_columns: Vec<String> = source_meta
        .map(|source| {
            source
                .primary_key
                .columns()
                .into_iter()
                .map(|c| c.to_string())
                .collect()
        })
        .unwrap_or_default();
    for col in &pk_columns {
        if !columns.contains(col) {
            columns.push(col.clone());
        }
    }

    // Scan all mappings that use this source dataset
    for mapping in &doc.mappings {
        let src_table = doc.sources.get(&mapping.source.dataset)
            .map(|s| s.table_name(&mapping.source.dataset).to_string())
            .unwrap_or_else(|| mapping.source.dataset.clone());
        if src_table != table_name {
            continue;
        }

        // Field source columns
        for fm in &mapping.fields {
            if let Some(ref src) = fm.source {
                if !columns.contains(src) {
                    columns.push(src.clone());
                }
            }
            // Per-field last_modified column
            if let Some(ref ts) = fm.last_modified {
                if let Some(field) = ts.field_name() {
                    let f = field.to_string();
                    if !columns.contains(&f) {
                        columns.push(f);
                    }
                }
            }
        }

        // Mapping-level last_modified column
        if let Some(ref ts) = mapping.last_modified {
            if let Some(field) = ts.field_name() {
                let f = field.to_string();
                if !columns.contains(&f) {
                    columns.push(f);
                }
            }
        }

        // cluster_field column
        if let Some(ref cf) = mapping.cluster_field {
            if !columns.contains(cf) {
                columns.push(cf.clone());
            }
        }
    }

    let mut col_defs: Vec<String> = Vec::new();
    if pk_columns.is_empty() {
        // Fallback for mappings without declared source PK metadata.
        col_defs.push("_row_id SERIAL PRIMARY KEY".to_string());
    }
    col_defs.extend(columns.iter().map(|c| format!("{} TEXT", qi(c))));
    if !pk_columns.is_empty() {
        col_defs.push(format!("PRIMARY KEY ({})", pk_columns.iter().map(|c| qi(c)).collect::<Vec<_>>().join(", ")));
    }

    format!(
        "-- Input table: {table_name}\n\
         CREATE TABLE IF NOT EXISTS {} (\n  {}\n);\n",
        qi(table_name),
        col_defs.join(",\n  ")
    )
}

// ---------------------------------------------------------------------------
// Annotation helpers — emit SQL comments showing user-defined configuration
// ---------------------------------------------------------------------------

use crate::model::{Mapping, Target, Strategy};

fn annotate_forward(m: &Mapping, _target: Option<&Target>) -> String {
    let mut lines = Vec::new();
    lines.push(format!("-- [annotate] _fwd_{}: {} -> {}", m.name, m.source.dataset, m.target.name()));
    for fm in &m.fields {
        if !fm.is_forward() { continue; }
        let tgt = fm.target.as_deref().unwrap_or("?");
        let src = fm.source.as_deref().unwrap_or("-");
        if let Some(ref e) = fm.expression {
            lines.push(format!("--   {src} -> {tgt} (expression: {e})"));
        } else {
            lines.push(format!("--   {src} -> {tgt}"));
        }
    }
    if let Some(ref f) = m.filter {
        lines.push(format!("--   filter: {f}"));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_identity(mappings: &[&Mapping], target: Option<&Target>) -> String {
    let mut lines = Vec::new();
    let target_name = mappings.first().map(|m| m.target.name()).unwrap_or("?");
    lines.push(format!("-- [annotate] _id_{target_name}: identity fields"));
    if let Some(t) = target {
        for (fname, fdef) in &t.fields {
            if fdef.strategy() == Strategy::Identity {
                lines.push(format!("--   {fname} (identity)"));
            }
        }
    }
    let names: Vec<&str> = mappings.iter().map(|m| m.name.as_str()).collect();
    lines.push(format!("--   sources: {}", names.join(", ")));
    for m in mappings {
        for fm in &m.fields {
            if !fm.is_forward() { continue; }
            let tgt = fm.target.as_deref().unwrap_or("?");
            let src = fm.source.as_deref().unwrap_or("-");
            let mut parts = vec![format!("{}: {} -> {}", m.name, src, tgt)];
            if let Some(ref e) = fm.expression {
                parts.push(format!("expression: {e}"));
            }
            if let Some(p) = fm.priority {
                parts.push(format!("priority: {p}"));
            }
            lines.push(format!("--   field: {}", parts.join(", ")));
        }
        if let Some(ref f) = m.filter {
            lines.push(format!("--   filter ({}): {f}", m.name));
        }
        if !m.links.is_empty() {
            for link in &m.links {
                lines.push(format!("--   link: {:?} -> references {}", link.field, link.references));
            }
        }
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_resolution(target: &Target) -> String {
    let mut lines = Vec::new();
    lines.push("-- [annotate] resolution strategies:".to_string());
    for (fname, fdef) in &target.fields {
        let strat = format!("{:?}", fdef.strategy()).to_lowercase();
        let mut parts = vec![format!("{fname}: {strat}")];
        if let Some(e) = fdef.expression() {
            parts.push(format!("expression: {e}"));
        }
        if let Some(g) = fdef.group() {
            parts.push(format!("group: {g}"));
        }
        if let Some(d) = fdef.default_expression() {
            parts.push(format!("default_expression: {d}"));
        } else if let Some(d) = fdef.default_value() {
            parts.push(format!("default: {d:?}"));
        }
        lines.push(format!("--   {}", parts.join(", ")));
    }
    lines.push(String::new());
    lines.join("\n")
}

fn annotate_reverse(m: &Mapping) -> String {
    let mut lines = Vec::new();
    lines.push(format!("-- [annotate] _rev_{}: reverse projection", m.name));
    for fm in &m.fields {
        if fm.is_reverse() {
            let tgt = fm.target.as_deref().unwrap_or("?");
            let src = fm.source.as_deref().unwrap_or("-");
            let mut parts = vec![format!("{tgt} -> {src}")];
            if let Some(ref e) = fm.reverse_expression {
                parts.push(format!("reverse_expression: {e}"));
            }
            if fm.reverse_required {
                parts.push("reverse_required".to_string());
            }
            lines.push(format!("--   field: {}", parts.join(", ")));
        }
    }
    if let Some(ref rf) = m.reverse_filter {
        lines.push(format!("--   reverse_filter: {rf}"));
    }
    lines.push(String::new());
    lines.join("\n")
}
