//! PostgreSQL view renderer for v2 mappings.
//!
//! View DAG (per target, per mapping):
//!
//!   sources           — input tables (provided by caller, not emitted)
//!     │
//!     ▼
//!   <mapping>_forward — source columns renamed to target shape, with
//!                       per-field priority columns and provenance
//!     │
//!     ▼
//!   <target>_identified — UNION ALL of forwards for the target, with
//!                         canonical_id assigned per identity cluster
//!     │
//!     ▼
//!   <target>          — one row per canonical entity, fields resolved
//!                       by per-field strategy (priority for coalesce)
//!     │
//!     ▼
//!   <mapping>_reverse — canonical projected back to source row shape,
//!                       LEFT JOINed against source on identity for PK
//!     │
//!     ▼
//!   <mapping>_updates — existing PK with changed columns
//!   <mapping>_inserts — canonical row with no matching source PK
//!   <mapping>_deletes — source row with no canonical match
//!
//! For Slice 1 (hello-world): single-field identity, single-field PK,
//! coalesce strategy, priority field-level resolution. Future slices
//! extend per example.

use crate::model::{Doc, IdentityGroup, Mapping, Strategy, Target};
use crate::qi;
use anyhow::{anyhow, Result};
use std::fmt::Write;

pub fn render_pg(doc: &Doc) -> Result<String> {
    // Slice 4 not yet rendered: cross-entity references on field maps.
    for m in &doc.mappings {
        for fm in &m.fields {
            if fm.references.is_some() {
                anyhow::bail!(
                    "pg: mapping `{}` field `{}` uses references: — slice 4 not yet implemented",
                    m.name,
                    fm.target
                );
            }
        }
        // Slice 3a constraint: a child mapping must declare both parent: and array:.
        if m.parent.is_some() != m.array.is_some() {
            anyhow::bail!(
                "pg: mapping `{}` must declare both parent: and array:, or neither",
                m.name
            );
        }
    }

    let mut out = String::new();

    writeln!(
        out,
        "-- Generated by osi-engine — PostgreSQL backend\n\
         -- Pipeline: forward (per mapping) → identified + resolved (per target)\n\
         --           → reverse (per mapping) → updates / inserts / deletes (per mapping)"
    )
    .unwrap();
    writeln!(out).unwrap();

    // 0. Virtual source views for child (nested) mappings — one per
    //    child mapping. Each expands the parent's array column via
    //    LATERAL jsonb_array_elements WITH ORDINALITY into one row per
    //    element; injects parent_fields aliases; synthesises `_row_pk`
    //    as `<parent_pk>:<ord>`.
    writeln!(
        out,
        "-- =====================================================================\n\
         -- 0. Virtual source views (per child mapping with parent:/array:)\n\
         -- ====================================================================="
    )
    .unwrap();
    writeln!(out).unwrap();
    for m in &doc.mappings {
        if m.parent.is_some() {
            render_child_source(&mut out, doc, m)?;
        }
    }

    // 1. Forward views — one per mapping.
    writeln!(
        out,
        "-- =====================================================================\n\
         -- 1. Forward views (per mapping)\n\
         --    Source columns renamed to target shape; per-field priority\n\
         --    columns and `_decl_order` for resolution tie-break.\n\
         -- ====================================================================="
    )
    .unwrap();
    writeln!(out).unwrap();
    for (idx, m) in doc.mappings.iter().enumerate() {
        render_forward(&mut out, doc, m, idx)?;
    }

    // 2. Identified + resolved views — one each per target.
    writeln!(
        out,
        "-- =====================================================================\n\
         -- 2. Identified + resolved views (per target)\n\
         --    `<T>_identified`: UNION ALL of forwards with `canonical_id`\n\
         --                      assigned per identity cluster.\n\
         --    `<T>`            : one row per canonical entity, fields resolved\n\
         --                      per strategy (priority + decl_order for coalesce).\n\
         -- ====================================================================="
    )
    .unwrap();
    writeln!(out).unwrap();
    for (target_name, target) in &doc.targets {
        render_identified(&mut out, doc, target_name, target)?;
        render_resolved(&mut out, doc, target_name, target)?;
    }

    // 3. Reverse + delta views — one set per mapping.
    writeln!(
        out,
        "-- =====================================================================\n\
         -- 3. Reverse + delta views (per mapping)\n\
         --    `<M>_reverse` : canonical projected back into source shape;\n\
         --                    LEFT JOIN against source on identity for PK.\n\
         --    `<M>_updates` : existing PK with column-level changes.\n\
         --    `<M>_inserts` : canonical row with no matching source PK.\n\
         --    `<M>_deletes` : source row with no canonical match.\n\
         -- ====================================================================="
    )
    .unwrap();
    writeln!(out).unwrap();
    for m in &doc.mappings {
        render_reverse(&mut out, doc, m)?;
        render_deltas(&mut out, doc, m)?;
    }

    Ok(out)
}

// ---------------------------------------------------------------------------
// 0. Helpers — mapping source resolution + child-source view rendering.
// ---------------------------------------------------------------------------

/// Resolve the SQL relation that supplies a mapping's input rows, plus
/// the column name that uniquely identifies a row inside it.
///
/// - Top-level mapping → real source table, source's primary key.
/// - Child mapping (`parent:` + `array:`) → its `<M>_source` virtual
///   view, with `_row_pk` as the synthetic identifier
///   (`<parent_pk>:<ord>`).
struct MappingSource {
    /// Quoted SQL identifier ready for `FROM` / `JOIN` use.
    table: String,
    /// Quoted PK column ready for SELECT / WHERE use.
    pk_col: String,
    /// Source name literal that goes into the forward view's `_src`
    /// column (always the underlying real source dataset).
    src_literal: String,
}

fn mapping_source(doc: &Doc, m: &Mapping) -> Result<MappingSource> {
    if m.parent.is_some() {
        Ok(MappingSource {
            table: qi(&format!("{}_source", m.name)),
            pk_col: qi("_row_pk"),
            src_literal: m.source.clone(),
        })
    } else {
        let src = doc
            .sources
            .get(&m.source)
            .ok_or_else(|| anyhow!("mapping {} references unknown source {}", m.name, m.source))?;
        Ok(MappingSource {
            table: qi(&m.source),
            pk_col: qi(&src.primary_key),
            src_literal: m.source.clone(),
        })
    }
}

/// Emit `<M>_source` for a child mapping: expands the parent's array
/// column via `LATERAL jsonb_array_elements ... WITH ORDINALITY` and
/// projects element fields, parent_fields aliases, and a synthetic
/// `_row_pk` (`<parent_pk>:<ord>`).
fn render_child_source(out: &mut String, doc: &Doc, m: &Mapping) -> Result<()> {
    let parent_name = m
        .parent
        .as_ref()
        .ok_or_else(|| anyhow!("render_child_source called on non-child mapping {}", m.name))?;
    let array_col = m
        .array
        .as_ref()
        .ok_or_else(|| anyhow!("child mapping {} missing array:", m.name))?;
    let parent = doc
        .mappings
        .iter()
        .find(|p| p.name == *parent_name)
        .ok_or_else(|| anyhow!("mapping {} parent: `{}` not found", m.name, parent_name))?;
    if parent.parent.is_some() {
        anyhow::bail!(
            "pg: mapping `{}` parent `{}` is itself nested; deep nesting (slice 3c) not yet implemented",
            m.name,
            parent_name
        );
    }
    let parent_src = doc.sources.get(&parent.source).ok_or_else(|| {
        anyhow!(
            "mapping {} parent source `{}` unknown",
            m.name,
            parent.source
        )
    })?;

    // Element fields: every distinct `fm.source` not already covered by
    // a `parent_fields:` alias. Read via `e.elem->>'<name>'`.
    let alias_keys: std::collections::HashSet<&str> =
        m.parent_fields.keys().map(|s| s.as_str()).collect();
    let mut element_fields = Vec::<String>::new();
    for fm in &m.fields {
        if alias_keys.contains(fm.source.as_str()) {
            continue;
        }
        if !element_fields.iter().any(|e| e == &fm.source) {
            element_fields.push(fm.source.clone());
        }
    }
    // Lift mapping-level last_modified column (if it isn't an alias).
    if let Some(lm) = &m.last_modified {
        if !alias_keys.contains(lm.as_str()) && !element_fields.iter().any(|e| e == lm) {
            element_fields.push(lm.clone());
        }
    }

    let view_name = qi(&format!("{}_source", m.name));
    writeln!(
        out,
        "-- Child source view: {} (expands `{}`.{} from parent `{}`)",
        m.name, parent.source, array_col, parent_name
    )
    .unwrap();
    writeln!(out, "CREATE VIEW {view_name} AS").unwrap();
    writeln!(out, "SELECT").unwrap();
    let parent_pk = qi(&parent_src.primary_key);
    let mut cols = Vec::<String>::new();
    cols.push(format!(
        "p.{parent_pk}::text || ':' || (ord - 1)::text AS \"_row_pk\""
    ));
    cols.push("(ord - 1)::int AS \"_ordinal\"".to_string());
    for (alias, parent_col) in &m.parent_fields {
        cols.push(format!("p.{} AS {}", qi(parent_col), qi(alias),));
    }
    for f in &element_fields {
        // Read element field via `->>` so result is text. JSONB sub-objects
        // collapse to their JSON encoding via `->>`. Adequate for slice 3a.
        cols.push(format!(
            "(e.elem ->> '{}') AS {}",
            f.replace('\'', "''"),
            qi(f),
        ));
    }
    for (i, c) in cols.iter().enumerate() {
        let comma = if i + 1 == cols.len() { "" } else { "," };
        writeln!(out, "  {c}{comma}").unwrap();
    }
    writeln!(out, "FROM {} p", qi(&parent.source)).unwrap();
    writeln!(
        out,
        "CROSS JOIN LATERAL jsonb_array_elements(p.{}::jsonb) WITH ORDINALITY AS e(elem, ord);",
        qi(array_col)
    )
    .unwrap();
    writeln!(out).unwrap();
    Ok(())
}

// ---------------------------------------------------------------------------
// 1. Forward view per mapping.
// ---------------------------------------------------------------------------

fn render_forward(out: &mut String, doc: &Doc, m: &Mapping, decl_order: usize) -> Result<()> {
    let ms = mapping_source(doc, m)?;
    let target = doc
        .targets
        .get(&m.target)
        .ok_or_else(|| anyhow!("mapping {} references unknown target {}", m.name, m.target))?;

    // SELECT columns:
    //   _decl_order::int           — declaration order (tie-break for resolution)
    //   _src::text                 — source name literal
    //   _src_pk::text              — synthetic or real PK cast to text
    //   _last_modified::timestamptz — row last-modified ts (NULL if mapping
    //                                doesn't declare `last_modified:`)
    //   for each target field f: f, f_priority::int (NULL if unspecified)
    let mut cols = Vec::<String>::new();
    cols.push(format!("{}::int AS _decl_order", decl_order));
    cols.push(format!(
        "'{}'::text AS _src",
        ms.src_literal.replace('\'', "''")
    ));
    cols.push(format!("{}::text AS _src_pk", ms.pk_col));
    let lm_expr = match &m.last_modified {
        Some(col) => format!("{}::timestamptz", qi(col)),
        None => "NULL::timestamptz".to_string(),
    };
    cols.push(format!("{lm_expr} AS _last_modified"));
    for (tname, _tdef) in &target.fields {
        let fm = m.fields.iter().find(|fm| fm.target == *tname);
        match fm {
            Some(fm) => {
                cols.push(format!("{} AS {}", qi(&fm.source), qi(tname)));
                let prio_lit = fm
                    .priority
                    .map(|p| format!("{}::int", p))
                    .unwrap_or_else(|| "NULL::int".to_string());
                cols.push(format!(
                    "{} AS {}",
                    prio_lit,
                    qi(&format!("{tname}_priority"))
                ));
            }
            None => {
                // Mapping doesn't provide this field — emit NULL.
                cols.push(format!("NULL::text AS {}", qi(tname)));
                cols.push(format!("NULL::int AS {}", qi(&format!("{tname}_priority"))));
            }
        }
    }

    let view_name = qi(&format!("{}_forward", m.name));
    writeln!(
        out,
        "-- Forward view: {} (source `{}` → target `{}`)",
        m.name, m.source, m.target
    )
    .unwrap();
    writeln!(out, "CREATE VIEW {view_name} AS").unwrap();
    writeln!(out, "SELECT").unwrap();
    for (i, c) in cols.iter().enumerate() {
        let comma = if i + 1 == cols.len() { "" } else { "," };
        writeln!(out, "  {c}{comma}").unwrap();
    }
    writeln!(out, "FROM {};", ms.table).unwrap();
    writeln!(out).unwrap();
    Ok(())
}

// ---------------------------------------------------------------------------
// 2a. Identified view — UNION ALL of forwards, with canonical_id.
// ---------------------------------------------------------------------------

fn render_identified(
    out: &mut String,
    doc: &Doc,
    target_name: &str,
    target: &Target,
) -> Result<()> {
    let mappings_for_target: Vec<&Mapping> = doc
        .mappings
        .iter()
        .filter(|m| m.target == target_name)
        .collect();
    if mappings_for_target.is_empty() {
        return Err(anyhow!("target {target_name} has no mappings"));
    }

    // Identity for slice 2: a single OR-group containing either a single
    // field or an AND-tuple of fields. The cluster key is built by
    // concatenating identity fields with a unit-separator so distinct
    // tuples never collide.
    let ident_fields: Vec<String> = match target.identity.as_slice() {
        [IdentityGroup::Single(f)] => vec![f.clone()],
        [IdentityGroup::Tuple(fs)] => fs.clone(),
        _ => {
            return Err(anyhow!(
                "target {target_name}: only single-field or one AND-tuple identity supported"
            ));
        }
    };
    let ident_expr = identity_concat_expr(&ident_fields);
    let ident_null_check = ident_fields
        .iter()
        .map(|f| format!("{} IS NULL", qi(f)))
        .collect::<Vec<_>>()
        .join(" OR ");

    let view_name = qi(&format!("{target_name}_identified"));
    writeln!(
        out,
        "-- Identified view: {target_name} (UNION ALL of forwards; canonical_id by identity {ident_fields:?})"
    )
    .unwrap();
    writeln!(out, "CREATE VIEW {view_name} AS").unwrap();
    writeln!(out, "WITH _all AS (").unwrap();
    for (i, m) in mappings_for_target.iter().enumerate() {
        let union = if i == 0 { "" } else { "  UNION ALL\n" };
        writeln!(
            out,
            "{union}  SELECT *, _src || ':' || _src_pk AS _row_id FROM {}",
            qi(&format!("{}_forward", m.name))
        )
        .unwrap();
    }
    writeln!(out, ")").unwrap();
    // canonical_id = MIN(_row_id) OVER identity-partition; rows where any
    // identity component is NULL get their own _row_id (singleton clusters).
    writeln!(out, "SELECT").unwrap();
    writeln!(out, "  *,").unwrap();
    writeln!(
        out,
        "  CASE WHEN ({ident_null_check}) THEN _row_id ELSE MIN(_row_id) OVER (PARTITION BY {ident_expr}) END AS canonical_id"
    )
    .unwrap();
    writeln!(out, "FROM _all;").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

/// SQL expression that concatenates identity field columns into a single
/// cluster key.  Single field renders as the column itself (preserving its
/// type); a tuple renders as `field1 || E'\\x1f' || field2 || ...` cast to
/// text via `concat_ws`-style coercion through `||`.
fn identity_concat_expr(fields: &[String]) -> String {
    if fields.len() == 1 {
        return qi(&fields[0]);
    }
    let mut parts: Vec<String> = Vec::new();
    for (i, f) in fields.iter().enumerate() {
        if i > 0 {
            parts.push("E'\\x1f'".to_string());
        }
        // Cast each component to text so concatenation is well-defined.
        parts.push(format!("{}::text", qi(f)));
    }
    parts.join(" || ")
}

// ---------------------------------------------------------------------------
// 2b. Resolved view — one row per canonical entity, fields by strategy.
// ---------------------------------------------------------------------------

fn render_resolved(out: &mut String, _doc: &Doc, target_name: &str, target: &Target) -> Result<()> {
    let view_name = qi(target_name);
    let identified = qi(&format!("{target_name}_identified"));
    writeln!(
        out,
        "-- Resolved view: {target_name} (per-canonical-entity, per-field strategy resolution)"
    )
    .unwrap();
    writeln!(out, "CREATE VIEW {view_name} AS").unwrap();
    writeln!(out, "WITH _ids AS (").unwrap();
    writeln!(out, "  SELECT DISTINCT canonical_id FROM {identified}").unwrap();
    writeln!(out, ")").unwrap();
    writeln!(out, "SELECT").unwrap();
    writeln!(out, "  _ids.canonical_id,").unwrap();
    let nfields = target.fields.len();
    for (i, (fname, fdef)) in target.fields.iter().enumerate() {
        let comma = if i + 1 == nfields { "" } else { "," };
        let resolved = match fdef.strategy {
            Strategy::Coalesce => format!(
                "(SELECT {field} FROM {identified} x \
                 WHERE x.canonical_id = _ids.canonical_id AND {field} IS NOT NULL \
                 ORDER BY {prio} NULLS LAST, x._decl_order LIMIT 1)",
                field = qi(fname),
                identified = identified,
                prio = qi(&format!("{fname}_priority")),
            ),
            Strategy::LastModified => format!(
                "(SELECT {field} FROM {identified} x \
                 WHERE x.canonical_id = _ids.canonical_id AND {field} IS NOT NULL \
                 ORDER BY x._last_modified DESC NULLS LAST, x._decl_order LIMIT 1)",
                field = qi(fname),
                identified = identified,
            ),
        };
        writeln!(out, "  {resolved} AS {}{comma}", qi(fname)).unwrap();
    }
    writeln!(out, "FROM _ids;").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

// ---------------------------------------------------------------------------
// 3a. Reverse view — canonical → source row shape.
// ---------------------------------------------------------------------------

fn render_reverse(out: &mut String, doc: &Doc, m: &Mapping) -> Result<()> {
    let target = doc
        .targets
        .get(&m.target)
        .ok_or_else(|| anyhow!("mapping {} references unknown target", m.name))?;
    let ms = mapping_source(doc, m)?;
    let is_child = m.parent.is_some();
    let pk_col_text = ms.pk_col.clone();
    let pk_in_fields = m.fields.iter().any(|fm| qi(&fm.source) == pk_col_text);

    let ident_fields: Vec<String> = match target.identity.as_slice() {
        [IdentityGroup::Single(f)] => vec![f.clone()],
        [IdentityGroup::Tuple(fs)] => fs.clone(),
        _ => {
            return Err(anyhow!(
                "mapping {}: only single-field or one AND-tuple identity supported",
                m.name
            ));
        }
    };

    // Slice 3b: locate child mappings whose parent is this mapping. Each
    // contributes a synthetic `<child.array>` jsonb_agg column.
    let children: Vec<&Mapping> = doc
        .mappings
        .iter()
        .filter(|c| c.parent.as_deref() == Some(m.name.as_str()) && c.array.is_some())
        .collect();

    // Assemble SELECT items + lateral-join items.
    let mut select_items: Vec<String> = Vec::new();
    let mut join_clauses: Vec<String> = Vec::new();

    select_items.push("c.canonical_id".to_string());
    select_items.push(format!("s.{pk_col_text} AS \"_src_pk\""));
    if !pk_in_fields && !is_child {
        select_items.push(format!("s.{pk_col_text} AS {pk_col_text}"));
    }
    for fm in &m.fields {
        select_items.push(format!(
            "c.{tgt} AS {srccol}",
            tgt = qi(&fm.target),
            srccol = qi(&fm.source)
        ));
    }
    // Synthetic child-array agg columns.
    for (idx, child) in children.iter().enumerate() {
        let array_col = child.array.as_ref().unwrap();
        let ch_alias = format!("ch_{idx}");
        let agg_col = build_child_agg_subquery(doc, m, child, &ch_alias)?;
        select_items.push(format!(
            "COALESCE({ch_alias}.{col}, '[]'::jsonb) AS {col}",
            col = qi(array_col)
        ));
        join_clauses.push(format!(
            "LEFT JOIN LATERAL (\n{agg_col}\n) {ch_alias} ON TRUE"
        ));
    }

    // Source LEFT JOIN.
    let mut on_clauses: Vec<String> = Vec::new();
    for ident_field in &ident_fields {
        let ident_src = m
            .fields
            .iter()
            .find(|fm| fm.target == *ident_field)
            .ok_or_else(|| {
                anyhow!(
                    "mapping {} does not map identity field {} of target {}",
                    m.name,
                    ident_field,
                    m.target
                )
            })?
            .source
            .clone();
        on_clauses.push(format!(
            "s.{src_ident} = c.{tgt_ident}",
            src_ident = qi(&ident_src),
            tgt_ident = qi(ident_field),
        ));
    }
    let source_join = format!(
        "LEFT JOIN {src} s ON {}",
        on_clauses.join(" AND "),
        src = ms.table
    );

    let view_name = qi(&format!("{}_reverse", m.name));
    writeln!(
        out,
        "-- Reverse view: {} (canonical `{}` → source `{}`)",
        m.name, m.target, m.source
    )
    .unwrap();
    writeln!(out, "CREATE VIEW {view_name} AS").unwrap();
    writeln!(out, "SELECT").unwrap();
    for (i, c) in select_items.iter().enumerate() {
        let comma = if i + 1 == select_items.len() { "" } else { "," };
        writeln!(out, "  {c}{comma}").unwrap();
    }
    writeln!(out, "FROM {} c", qi(&m.target)).unwrap();
    writeln!(out, "{source_join}").unwrap();
    for jc in &join_clauses {
        writeln!(out, "{jc}").unwrap();
    }
    writeln!(out, ";").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

/// Build the body of the `LEFT JOIN LATERAL (...)` subquery that
/// aggregates `child`'s resolved canonical rows into a `jsonb_agg`
/// keyed at the parent's identity. Returns the SELECT statement
/// (no surrounding parens).
fn build_child_agg_subquery(
    doc: &Doc,
    parent: &Mapping,
    child: &Mapping,
    cl_alias: &str,
) -> Result<String> {
    let array_col = child.array.as_ref().unwrap();
    let _ = array_col;
    let child_target = doc
        .targets
        .get(&child.target)
        .ok_or_else(|| anyhow!("mapping {} → unknown target {}", child.name, child.target))?;

    // Element fields = child.fields whose source is NOT a parent_fields alias.
    let alias_keys: std::collections::HashSet<&str> =
        child.parent_fields.keys().map(|s| s.as_str()).collect();
    let mut obj_pairs: Vec<String> = Vec::new();
    for fm in &child.fields {
        if alias_keys.contains(fm.source.as_str()) {
            continue;
        }
        obj_pairs.push(format!(
            "'{key}', {cl_alias}.{tgt}",
            key = fm.source.replace('\'', "''"),
            tgt = qi(&fm.target),
        ));
    }

    // ORDER BY child target's identity components (in declared order).
    let mut order_cols: Vec<String> = Vec::new();
    for ig in &child_target.identity {
        match ig {
            IdentityGroup::Single(f) => order_cols.push(format!("{cl_alias}.{}", qi(f))),
            IdentityGroup::Tuple(fs) => {
                for f in fs {
                    order_cols.push(format!("{cl_alias}.{}", qi(f)));
                }
            }
        }
    }
    let order_by = if order_cols.is_empty() {
        String::new()
    } else {
        format!(" ORDER BY {}", order_cols.join(", "))
    };

    // JOIN: child's parent_fields aliases (resolved to child target columns)
    //       equal parent's resolved columns for the same parent source col.
    let mut where_clauses: Vec<String> = Vec::new();
    for (alias, parent_col) in &child.parent_fields {
        let alias_target = child
            .fields
            .iter()
            .find(|fm| fm.source == *alias)
            .ok_or_else(|| {
                anyhow!(
                    "child {}: parent_fields alias `{}` is not declared in fields",
                    child.name,
                    alias
                )
            })?
            .target
            .clone();
        let parent_target = parent
            .fields
            .iter()
            .find(|fm| fm.source == *parent_col)
            .ok_or_else(|| {
                anyhow!(
                    "parent {}: parent_fields refers to source column `{}` not mapped by parent",
                    parent.name,
                    parent_col
                )
            })?
            .target
            .clone();
        where_clauses.push(format!(
            "{cl_alias}.{lhs} = c.{rhs}",
            lhs = qi(&alias_target),
            rhs = qi(&parent_target),
        ));
    }
    let where_clause = if where_clauses.is_empty() {
        "TRUE".to_string()
    } else {
        where_clauses.join(" AND ")
    };

    let array_col_qi = qi(array_col);
    Ok(format!(
        "  SELECT jsonb_agg(jsonb_build_object({pairs}){order}) AS {col}\n  FROM {tgt} {cl_alias}\n  WHERE {where_clause}",
        pairs = obj_pairs.join(", "),
        order = order_by,
        col = array_col_qi,
        tgt = qi(&child.target),
    ))
}

// ---------------------------------------------------------------------------
// 3b. Delta views — updates / inserts / deletes.
// ---------------------------------------------------------------------------

fn render_deltas(out: &mut String, doc: &Doc, m: &Mapping) -> Result<()> {
    let ms = mapping_source(doc, m)?;
    let pk = ms.pk_col.clone();
    let reverse = qi(&format!("{}_reverse", m.name));
    let source = ms.table.clone();
    // Child mappings: `_row_pk` is an internal join key, not a user-visible
    // column. Suppress it from delta-view SELECTs.
    let is_child = m.parent.is_some();
    let pk_in_fields = m.fields.iter().any(|fm| qi(&fm.source) == pk);
    // Visible PK column emitted in deltas: top-level only, and only
    // when the PK column isn't already a mapped source column.
    let emit_visible_pk = !is_child && !pk_in_fields;
    let pk_select = if emit_visible_pk {
        format!(", r.{pk}")
    } else {
        String::new()
    };

    // Round-trip columns: regular mapped fields plus child-array agg
    // columns where this mapping is the parent. Both sides of the
    // round-trip diff must agree on these.
    let mut roundtrip_cols: Vec<String> = m.fields.iter().map(|fm| fm.source.clone()).collect();
    for child in &doc.mappings {
        if child.parent.as_deref() == Some(m.name.as_str()) {
            if let Some(arr) = &child.array {
                if !roundtrip_cols.iter().any(|c| c == arr) {
                    roundtrip_cols.push(arr.clone());
                }
            }
        }
    }

    // updates: PK match + at least one column DISTINCT FROM
    let updates_view = qi(&format!("{}_updates", m.name));
    writeln!(
        out,
        "-- Delta `updates`: source row whose reverse projection differs from current source row"
    )
    .unwrap();
    writeln!(out, "CREATE VIEW {updates_view} AS").unwrap();
    writeln!(out, "SELECT r.canonical_id{pk_select}").unwrap();
    for col in &roundtrip_cols {
        writeln!(out, "  , r.{}", qi(col)).unwrap();
    }
    writeln!(out, "FROM {reverse} r").unwrap();
    writeln!(out, "JOIN {source} s ON s.{pk} = r.\"_src_pk\"").unwrap();
    writeln!(out, "WHERE r.\"_src_pk\" IS NOT NULL AND (").unwrap();
    let nfields = roundtrip_cols.len();
    for (i, col) in roundtrip_cols.iter().enumerate() {
        let or = if i + 1 == nfields { "" } else { " OR" };
        writeln!(out, "  s.{col} IS DISTINCT FROM r.{col}{or}", col = qi(col)).unwrap();
    }
    writeln!(out, ");").unwrap();
    writeln!(out).unwrap();

    // inserts: rows in reverse with no PK
    let inserts_view = qi(&format!("{}_inserts", m.name));
    writeln!(
        out,
        "-- Delta `inserts`: canonical entities with no existing source row in this mapping"
    )
    .unwrap();
    writeln!(out, "CREATE VIEW {inserts_view} AS").unwrap();
    writeln!(out, "SELECT r.canonical_id{pk_select}").unwrap();
    for col in &roundtrip_cols {
        writeln!(out, "  , r.{}", qi(col)).unwrap();
    }
    writeln!(out, "FROM {reverse} r WHERE r.\"_src_pk\" IS NULL;").unwrap();
    writeln!(out).unwrap();

    // deletes: rows in source with no canonical reverse projection.
    let deletes_view = qi(&format!("{}_deletes", m.name));
    writeln!(
        out,
        "-- Delta `deletes`: source rows whose canonical entity has disappeared"
    )
    .unwrap();
    writeln!(out, "CREATE VIEW {deletes_view} AS").unwrap();
    let mut delete_cols: Vec<String> = Vec::new();
    if emit_visible_pk {
        delete_cols.push(format!("s.{pk}"));
    }
    for col in &roundtrip_cols {
        delete_cols.push(format!("s.{}", qi(col)));
    }
    if delete_cols.is_empty() {
        delete_cols.push("NULL::text AS _empty".to_string());
    }
    writeln!(out, "SELECT {}", delete_cols.join(", ")).unwrap();
    writeln!(out, "FROM {source} s").unwrap();
    writeln!(
        out,
        "LEFT JOIN {reverse} r ON r.\"_src_pk\" = s.{pk} WHERE r.\"_src_pk\" IS NULL;"
    )
    .unwrap();
    writeln!(out).unwrap();

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_str;

    fn hello_world_yaml() -> &'static str {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../examples/hello-world/mapping.yaml"
        );
        // Note: include_str! requires path literal; use std::fs at runtime.
        let _ = path;
        ""
    }

    #[test]
    fn renders_hello_world_smoke() {
        // Smoke test: render produces a non-empty string with all expected views.
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("examples/hello-world/mapping.yaml");
        let yaml = std::fs::read_to_string(&path).unwrap();
        let _ = hello_world_yaml(); // silence unused
        let doc = parse_str(&yaml).unwrap();
        let sql = render_pg(&doc).unwrap();
        for needle in &[
            "\"crm_forward\"",
            "\"erp_forward\"",
            "\"contact_identified\"",
            "\"contact\"",
            "\"crm_reverse\"",
            "\"erp_reverse\"",
            "\"crm_updates\"",
            "\"erp_inserts\"",
            "canonical_id",
        ] {
            assert!(sql.contains(needle), "missing {needle} in:\n{sql}");
        }
    }
}
