pub mod forward;
pub mod identity;
pub mod resolution;
pub mod reverse;
pub mod delta;

use anyhow::Result;

use crate::dag::{ViewDag, ViewNode};
use crate::model::MappingDocument;

/// Render the complete SQL script for a mapping document.
///
/// When `create_tables` is true, emits `CREATE TABLE` statements for all
/// input tables (source datasets and cluster_members tables) so the output
/// is self-contained and can be executed in an empty Postgres database.
pub fn render_sql(doc: &MappingDocument, dag: &ViewDag, create_tables: bool) -> Result<String> {
    let mut sql = String::new();

    sql.push_str("-- Generated by osi-engine — OSI mapping reference engine\n");
    sql.push_str("-- Do not edit manually.\n\n");
    sql.push_str("BEGIN;\n\n");

    for node in &dag.order {
        match node {
            ViewNode::Source(table_name) => {
                if create_tables {
                    sql.push_str(&render_input_table(doc, table_name));
                    sql.push('\n');
                }
            }
            ViewNode::Forward(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                let source_meta = doc.sources.get(&mapping.source.dataset);
                let target = doc.targets.get(mapping.target.name());
                sql.push_str(&forward::render_forward_view(mapping, source_meta, target)?);
                sql.push('\n');
            }
            ViewNode::Identity(target_name) => {
                let target = doc.targets.get(target_name);
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                sql.push_str(&identity::render_identity_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.mappings,
                    &doc.sources,
                )?);
                sql.push('\n');
            }
            ViewNode::Resolved(target_name) => {
                let target = doc
                    .targets
                    .get(target_name)
                    .expect("target exists in dag");
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                sql.push_str(&resolution::render_resolution_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.targets,
                )?);
                sql.push('\n');
            }
            ViewNode::Reverse(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                let target_name = mapping.target.name();
                let target = doc.targets.get(target_name);
                let source_meta = doc.sources.get(&mapping.source.dataset);
                sql.push_str(&reverse::render_reverse_view(
                    mapping,
                    target_name,
                    target,
                    &doc.targets,
                    source_meta,
                )?);
                sql.push('\n');
            }
            ViewNode::Delta(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                let source_meta = doc.sources.get(&mapping.source.dataset);
                sql.push_str(&delta::render_delta_view(mapping, source_meta)?);
                sql.push('\n');
            }
        }
    }

    sql.push_str("COMMIT;\n");

    Ok(sql)
}

/// Render a CREATE TABLE statement for an input table.
///
/// For source datasets: emits `_row_id SERIAL` + PK columns + all source
/// columns referenced by field mappings + timestamp columns.
///
/// For cluster_members tables: emits the cluster_id and source_key columns.
///
/// All columns are typed TEXT (the actual types depend on the source system
/// and are not declared in the mapping YAML).
fn render_input_table(doc: &MappingDocument, table_name: &str) -> String {
    // Check if this is a cluster_members table
    for mapping in &doc.mappings {
        if let Some(ref cm) = mapping.cluster_members {
            if cm.table_name(&mapping.name) == table_name {
                return format!(
                    "-- Input table: {table_name} (cluster members)\n\
                     CREATE TABLE IF NOT EXISTS {table_name} (\n  \
                       {} TEXT,\n  \
                       {} TEXT\n\
                     );\n",
                    cm.source_key, cm.cluster_id
                );
            }
        }
    }

    // Source dataset table — collect all referenced columns
    let mut columns: Vec<String> = Vec::new();

    // Find source metadata for PK
    if let Some(source) = doc.sources.get(table_name) {
        for col in source.primary_key.columns() {
            if !columns.contains(&col.to_string()) {
                columns.push(col.to_string());
            }
        }
    }
    // Also check via Source.table_name override
    let source_meta = doc.sources.iter().find(|(key, src)| {
        src.table_name(key) == table_name
    });
    if let Some((_key, source)) = source_meta {
        for col in source.primary_key.columns() {
            if !columns.contains(&col.to_string()) {
                columns.push(col.to_string());
            }
        }
    }

    // Scan all mappings that use this source dataset
    for mapping in &doc.mappings {
        let src_table = doc.sources.get(&mapping.source.dataset)
            .map(|s| s.table_name(&mapping.source.dataset).to_string())
            .unwrap_or_else(|| mapping.source.dataset.clone());
        if src_table != table_name {
            continue;
        }

        // Field source columns
        for fm in &mapping.fields {
            if let Some(ref src) = fm.source {
                if !columns.contains(src) {
                    columns.push(src.clone());
                }
            }
            // Per-field last_modified column
            if let Some(ref ts) = fm.last_modified {
                if let Some(field) = ts.field_name() {
                    let f = field.to_string();
                    if !columns.contains(&f) {
                        columns.push(f);
                    }
                }
            }
        }

        // Mapping-level last_modified column
        if let Some(ref ts) = mapping.last_modified {
            if let Some(field) = ts.field_name() {
                let f = field.to_string();
                if !columns.contains(&f) {
                    columns.push(f);
                }
            }
        }

        // cluster_field column
        if let Some(ref cf) = mapping.cluster_field {
            if !columns.contains(cf) {
                columns.push(cf.clone());
            }
        }
    }

    let col_defs: Vec<String> = std::iter::once("_row_id SERIAL PRIMARY KEY".to_string())
        .chain(columns.iter().map(|c| format!("{c} TEXT")))
        .collect();

    format!(
        "-- Input table: {table_name}\n\
         CREATE TABLE IF NOT EXISTS {table_name} (\n  {}\n);\n",
        col_defs.join(",\n  ")
    )
}
