pub mod forward;
pub mod identity;
pub mod resolution;
pub mod reverse;
pub mod delta;

use anyhow::Result;

use crate::dag::{ViewDag, ViewNode};
use crate::model::MappingDocument;

/// Render the complete SQL script for a mapping document.
pub fn render_sql(doc: &MappingDocument, dag: &ViewDag) -> Result<String> {
    let mut sql = String::new();

    sql.push_str("-- Generated by osi-engine — OSI mapping reference engine\n");
    sql.push_str("-- Do not edit manually.\n\n");
    sql.push_str("BEGIN;\n\n");

    for node in &dag.order {
        match node {
            ViewNode::Source(_) => {
                // External table — nothing to create
            }
            ViewNode::Forward(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                let target = doc.targets.get(mapping.target.name());
                sql.push_str(&forward::render_forward_view(mapping, target)?);
                sql.push('\n');
            }
            ViewNode::Identity(target_name) => {
                let target = doc.targets.get(target_name);
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                sql.push_str(&identity::render_identity_view(
                    target_name,
                    target,
                    &mappings,
                )?);
                sql.push('\n');
            }
            ViewNode::Resolved(target_name) => {
                let target = doc
                    .targets
                    .get(target_name)
                    .expect("target exists in dag");
                let mappings: Vec<_> = doc
                    .mappings
                    .iter()
                    .filter(|m| m.target.name() == target_name)
                    .collect();
                sql.push_str(&resolution::render_resolution_view(
                    target_name,
                    target,
                    &mappings,
                    &doc.targets,
                )?);
                sql.push('\n');
            }
            ViewNode::Reverse(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                let target_name = mapping.target.name();
                let target = doc.targets.get(target_name);
                sql.push_str(&reverse::render_reverse_view(
                    mapping,
                    target_name,
                    target,
                    &doc.targets,
                )?);
                sql.push('\n');
            }
            ViewNode::Delta(mapping_name) => {
                let mapping = doc
                    .mappings
                    .iter()
                    .find(|m| &m.name == mapping_name)
                    .expect("mapping exists in dag");
                sql.push_str(&delta::render_delta_view(mapping)?);
                sql.push('\n');
            }
        }
    }

    sql.push_str("COMMIT;\n");

    Ok(sql)
}
